// Automatically generated by gen-errcodes.rb at 2024-10-15 21:40:52 UTC
//
// DO NOT EDIT MANUALLY !!!
//

#[repr(u32)]
#[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum SqlState {

    /* Section: Class 00 - Successful Completion */
    /** SQLSTATE: `00000` */ SuccessfulCompletion = 0x0,

    /* Section: Class 01 - Warning */
    /** SQLSTATE: `01000` */ Warning = 0x40000,
    /** SQLSTATE: `0100C` */ WarningDynamicResultSetsReturned = 0x40013,
    /** SQLSTATE: `01008` */ WarningImplicitZeroBitPadding = 0x40008,
    /** SQLSTATE: `01003` */ WarningNullValueEliminatedInSetFunction = 0x40003,
    /** SQLSTATE: `01007` */ WarningPrivilegeNotGranted = 0x40007,
    /** SQLSTATE: `01006` */ WarningPrivilegeNotRevoked = 0x40006,
    /** SQLSTATE: `01004` */ WarningStringDataRightTruncation = 0x40004,
    /** SQLSTATE: `01P01` */ WarningDeprecatedFeature = 0x60001,

    /* Section: Class 02 - No Data (this is also a warning class per the SQL standard) */
    /** SQLSTATE: `02000` */ NoData = 0x80000,
    /** SQLSTATE: `02001` */ NoAdditionalDynamicResultSetsReturned = 0x80001,

    /* Section: Class 03 - SQL Statement Not Yet Complete */
    /** SQLSTATE: `03000` */ SqlStatementNotYetComplete = 0xc0000,

    /* Section: Class 08 - Connection Exception */
    /** SQLSTATE: `08000` */ ConnectionException = 0x200000,
    /** SQLSTATE: `08003` */ ConnectionDoesNotExist = 0x200003,
    /** SQLSTATE: `08006` */ ConnectionFailure = 0x200006,
    /** SQLSTATE: `08001` */ SqlclientUnableToEstablishSqlconnection = 0x200001,
    /** SQLSTATE: `08004` */ SqlserverRejectedEstablishmentOfSqlconnection = 0x200004,
    /** SQLSTATE: `08007` */ TransactionResolutionUnknown = 0x200007,
    /** SQLSTATE: `08P01` */ ProtocolViolation = 0x220001,

    /* Section: Class 09 - Triggered Action Exception */
    /** SQLSTATE: `09000` */ TriggeredActionException = 0x240000,

    /* Section: Class 0A - Feature Not Supported */
    /** SQLSTATE: `0A000` */ FeatureNotSupported = 0x440000,

    /* Section: Class 0B - Invalid Transaction Initiation */
    /** SQLSTATE: `0B000` */ InvalidTransactionInitiation = 0x480000,

    /* Section: Class 0F - Locator Exception */
    /** SQLSTATE: `0F000` */ LocatorException = 0x580000,
    /** SQLSTATE: `0F001` */ LEInvalidSpecification = 0x580001,

    /* Section: Class 0L - Invalid Grantor */
    /** SQLSTATE: `0L000` */ InvalidGrantor = 0x700000,
    /** SQLSTATE: `0LP01` */ InvalidGrantOperation = 0x720001,

    /* Section: Class 0P - Invalid Role Specification */
    /** SQLSTATE: `0P000` */ InvalidRoleSpecification = 0x800000,

    /* Section: Class 0Z - Diagnostics Exception */
    /** SQLSTATE: `0Z000` */ DiagnosticsException = 0xa80000,
    /** SQLSTATE: `0Z002` */ StackedDiagnosticsAccessedWithoutActiveHandler = 0xa80002,

    /* Section: Class 10 - XQuery Error */
    /** SQLSTATE: `10608` */ InvalidArgumentForXquery = 0x1006008,

    /* Section: Class 20 - Case Not Found */
    /** SQLSTATE: `20000` */ CaseNotFound = 0x2000000,

    /* Section: Class 21 - Cardinality Violation */
    /** SQLSTATE: `21000` */ CardinalityViolation = 0x2040000,

    /* Section: Class 22 - Data Exception */
    /** SQLSTATE: `22000` */ DataException = 0x2080000,
    /// Alias: `ArrayElementError`<p/>
    /** SQLSTATE: `2202E` */ ArraySubscriptError = 0x2080095,
    /** SQLSTATE: `22021` */ CharacterNotInRepertoire = 0x2080081,
    /// Alias: `DatetimeValueOutOfRange`<p/>
    /** SQLSTATE: `22008` */ DatetimeFieldOverflow = 0x2080008,
    /** SQLSTATE: `22012` */ DivisionByZero = 0x2080042,
    /** SQLSTATE: `22005` */ ErrorInAssignment = 0x2080005,
    /** SQLSTATE: `2200B` */ EscapeCharacterConflict = 0x2080012,
    /** SQLSTATE: `22022` */ IndicatorOverflow = 0x2080082,
    /** SQLSTATE: `22015` */ IntervalFieldOverflow = 0x2080045,
    /** SQLSTATE: `2201E` */ InvalidArgumentForLog = 0x2080055,
    /** SQLSTATE: `22014` */ InvalidArgumentForNtile = 0x2080044,
    /** SQLSTATE: `22016` */ InvalidArgumentForNthValue = 0x2080046,
    /** SQLSTATE: `2201F` */ InvalidArgumentForPowerFunction = 0x2080056,
    /** SQLSTATE: `2201G` */ InvalidArgumentForWidthBucketFunction = 0x2080057,
    /** SQLSTATE: `22018` */ InvalidCharacterValueForCast = 0x2080048,
    /** SQLSTATE: `22007` */ InvalidDatetimeFormat = 0x2080007,
    /** SQLSTATE: `22019` */ InvalidEscapeCharacter = 0x2080049,
    /** SQLSTATE: `2200D` */ InvalidEscapeOctet = 0x2080014,
    /** SQLSTATE: `22025` */ InvalidEscapeSequence = 0x2080085,
    /** SQLSTATE: `22P06` */ NonstandardUseOfEscapeCharacter = 0x20a0006,
    /** SQLSTATE: `22010` */ InvalidIndicatorParameterValue = 0x2080040,
    /** SQLSTATE: `22023` */ InvalidParameterValue = 0x2080083,
    /** SQLSTATE: `22013` */ InvalidPrecedingOrFollowingSize = 0x2080043,
    /** SQLSTATE: `2201B` */ InvalidRegularExpression = 0x2080052,
    /** SQLSTATE: `2201W` */ InvalidRowCountInLimitClause = 0x2080067,
    /** SQLSTATE: `2201X` */ InvalidRowCountInResultOffsetClause = 0x2080068,
    /** SQLSTATE: `2202H` */ InvalidTablesampleArgument = 0x2080098,
    /** SQLSTATE: `2202G` */ InvalidTablesampleRepeat = 0x2080097,
    /** SQLSTATE: `22009` */ InvalidTimeZoneDisplacementValue = 0x2080009,
    /** SQLSTATE: `2200C` */ InvalidUseOfEscapeCharacter = 0x2080013,
    /** SQLSTATE: `2200G` */ MostSpecificTypeMismatch = 0x2080017,
    /** SQLSTATE: `22004` */ NullValueNotAllowed = 0x2080004,
    /** SQLSTATE: `22002` */ NullValueNoIndicatorParameter = 0x2080002,
    /** SQLSTATE: `22003` */ NumericValueOutOfRange = 0x2080003,
    /** SQLSTATE: `2200H` */ SequenceGeneratorLimitExceeded = 0x2080018,
    /** SQLSTATE: `22026` */ StringDataLengthMismatch = 0x2080086,
    /** SQLSTATE: `22001` */ StringDataRightTruncation = 0x2080001,
    /** SQLSTATE: `22011` */ SubstringError = 0x2080041,
    /** SQLSTATE: `22027` */ TrimError = 0x2080087,
    /** SQLSTATE: `22024` */ UnterminatedCString = 0x2080084,
    /** SQLSTATE: `2200F` */ ZeroLengthCharacterString = 0x2080016,
    /** SQLSTATE: `22P01` */ FloatingPointException = 0x20a0001,
    /** SQLSTATE: `22P02` */ InvalidTextRepresentation = 0x20a0002,
    /** SQLSTATE: `22P03` */ InvalidBinaryRepresentation = 0x20a0003,
    /** SQLSTATE: `22P04` */ BadCopyFileFormat = 0x20a0004,
    /** SQLSTATE: `22P05` */ UntranslatableCharacter = 0x20a0005,
    /** SQLSTATE: `2200L` */ NotAnXmlDocument = 0x208001c,
    /** SQLSTATE: `2200M` */ InvalidXmlDocument = 0x208001d,
    /** SQLSTATE: `2200N` */ InvalidXmlContent = 0x208001e,
    /** SQLSTATE: `2200S` */ InvalidXmlComment = 0x2080023,
    /** SQLSTATE: `2200T` */ InvalidXmlProcessingInstruction = 0x2080024,
    /** SQLSTATE: `22030` */ DuplicateJsonObjectKeyValue = 0x20800c0,
    /** SQLSTATE: `22031` */ InvalidArgumentForSqlJsonDatetimeFunction = 0x20800c1,
    /** SQLSTATE: `22032` */ InvalidJsonText = 0x20800c2,
    /** SQLSTATE: `22033` */ InvalidSqlJsonSubscript = 0x20800c3,
    /** SQLSTATE: `22034` */ MoreThanOneSqlJsonItem = 0x20800c4,
    /** SQLSTATE: `22035` */ NoSqlJsonItem = 0x20800c5,
    /** SQLSTATE: `22036` */ NonNumericSqlJsonItem = 0x20800c6,
    /** SQLSTATE: `22037` */ NonUniqueKeysInAJsonObject = 0x20800c7,
    /** SQLSTATE: `22038` */ SingletonSqlJsonItemRequired = 0x20800c8,
    /** SQLSTATE: `22039` */ SqlJsonArrayNotFound = 0x20800c9,
    /** SQLSTATE: `2203A` */ SqlJsonMemberNotFound = 0x20800d1,
    /** SQLSTATE: `2203B` */ SqlJsonNumberNotFound = 0x20800d2,
    /** SQLSTATE: `2203C` */ SqlJsonObjectNotFound = 0x20800d3,
    /** SQLSTATE: `2203D` */ TooManyJsonArrayElements = 0x20800d4,
    /** SQLSTATE: `2203E` */ TooManyJsonObjectMembers = 0x20800d5,
    /** SQLSTATE: `2203F` */ SqlJsonScalarRequired = 0x20800d6,
    /** SQLSTATE: `2203G` */ SqlJsonItemCannotBeCastToTargetType = 0x20800d7,

    /* Section: Class 23 - Integrity Constraint Violation */
    /** SQLSTATE: `23000` */ IntegrityConstraintViolation = 0x20c0000,
    /** SQLSTATE: `23001` */ RestrictViolation = 0x20c0001,
    /** SQLSTATE: `23502` */ NotNullViolation = 0x20c5002,
    /** SQLSTATE: `23503` */ ForeignKeyViolation = 0x20c5003,
    /** SQLSTATE: `23505` */ UniqueViolation = 0x20c5005,
    /** SQLSTATE: `23514` */ CheckViolation = 0x20c5044,
    /** SQLSTATE: `23P01` */ ExclusionViolation = 0x20e0001,

    /* Section: Class 24 - Invalid Cursor State */
    /** SQLSTATE: `24000` */ InvalidCursorState = 0x2100000,

    /* Section: Class 25 - Invalid Transaction State */
    /** SQLSTATE: `25000` */ InvalidTransactionState = 0x2140000,
    /** SQLSTATE: `25001` */ ActiveSqlTransaction = 0x2140001,
    /** SQLSTATE: `25002` */ BranchTransactionAlreadyActive = 0x2140002,
    /** SQLSTATE: `25008` */ HeldCursorRequiresSameIsolationLevel = 0x2140008,
    /** SQLSTATE: `25003` */ InappropriateAccessModeForBranchTransaction = 0x2140003,
    /** SQLSTATE: `25004` */ InappropriateIsolationLevelForBranchTransaction = 0x2140004,
    /** SQLSTATE: `25005` */ NoActiveSqlTransactionForBranchTransaction = 0x2140005,
    /** SQLSTATE: `25006` */ ReadOnlySqlTransaction = 0x2140006,
    /** SQLSTATE: `25007` */ SchemaAndDataStatementMixingNotSupported = 0x2140007,
    /** SQLSTATE: `25P01` */ NoActiveSqlTransaction = 0x2160001,
    /** SQLSTATE: `25P02` */ InFailedSqlTransaction = 0x2160002,
    /** SQLSTATE: `25P03` */ IdleInTransactionSessionTimeout = 0x2160003,
    /** SQLSTATE: `25P04` */ TransactionTimeout = 0x2160004,

    /* Section: Class 26 - Invalid SQL Statement Name */
    /// Alias: `UndefinedPstatement`<p/>
    /** SQLSTATE: `26000` */ InvalidSqlStatementName = 0x2180000,

    /* Section: Class 27 - Triggered Data Change Violation */
    /** SQLSTATE: `27000` */ TriggeredDataChangeViolation = 0x21c0000,

    /* Section: Class 28 - Invalid Authorization Specification */
    /** SQLSTATE: `28000` */ InvalidAuthorizationSpecification = 0x2200000,
    /** SQLSTATE: `28P01` */ InvalidPassword = 0x2220001,

    /* Section: Class 2B - Dependent Privilege Descriptors Still Exist */
    /** SQLSTATE: `2B000` */ DependentPrivilegeDescriptorsStillExist = 0x2480000,
    /** SQLSTATE: `2BP01` */ DependentObjectsStillExist = 0x24a0001,

    /* Section: Class 2D - Invalid Transaction Termination */
    /** SQLSTATE: `2D000` */ InvalidTransactionTermination = 0x2500000,

    /* Section: Class 2F - SQL Routine Exception */
    /** SQLSTATE: `2F000` */ SqlRoutineException = 0x2580000,
    /** SQLSTATE: `2F005` */ SREFunctionExecutedNoReturnStatement = 0x2580005,
    /** SQLSTATE: `2F002` */ SREModifyingSqlDataNotPermitted = 0x2580002,
    /** SQLSTATE: `2F003` */ SREProhibitedSqlStatementAttempted = 0x2580003,
    /** SQLSTATE: `2F004` */ SREReadingSqlDataNotPermitted = 0x2580004,

    /* Section: Class 34 - Invalid Cursor Name */
    /// Alias: `UndefinedCursor`<p/>
    /** SQLSTATE: `34000` */ InvalidCursorName = 0x3100000,

    /* Section: Class 38 - External Routine Exception */
    /** SQLSTATE: `38000` */ ExternalRoutineException = 0x3200000,
    /** SQLSTATE: `38001` */ EREContainingSqlNotPermitted = 0x3200001,
    /** SQLSTATE: `38002` */ EREModifyingSqlDataNotPermitted = 0x3200002,
    /** SQLSTATE: `38003` */ EREProhibitedSqlStatementAttempted = 0x3200003,
    /** SQLSTATE: `38004` */ EREReadingSqlDataNotPermitted = 0x3200004,

    /* Section: Class 39 - External Routine Invocation Exception */
    /** SQLSTATE: `39000` */ ExternalRoutineInvocationException = 0x3240000,
    /** SQLSTATE: `39001` */ ERIEInvalidSqlstateReturned = 0x3240001,
    /** SQLSTATE: `39004` */ ERIENullValueNotAllowed = 0x3240004,
    /** SQLSTATE: `39P01` */ ERIETriggerProtocolViolated = 0x3260001,
    /** SQLSTATE: `39P02` */ ERIESrfProtocolViolated = 0x3260002,
    /** SQLSTATE: `39P03` */ ERIEEventTriggerProtocolViolated = 0x3260003,

    /* Section: Class 3B - Savepoint Exception */
    /** SQLSTATE: `3B000` */ SavepointException = 0x3480000,
    /** SQLSTATE: `3B001` */ SEInvalidSpecification = 0x3480001,

    /* Section: Class 3D - Invalid Catalog Name */
    /// Alias: `UndefinedDatabase`<p/>
    /** SQLSTATE: `3D000` */ InvalidCatalogName = 0x3500000,

    /* Section: Class 3F - Invalid Schema Name */
    /// Alias: `UndefinedSchema`<p/>
    /** SQLSTATE: `3F000` */ InvalidSchemaName = 0x3580000,

    /* Section: Class 40 - Transaction Rollback */
    /** SQLSTATE: `40000` */ TransactionRollback = 0x4000000,
    /** SQLSTATE: `40002` */ TRIntegrityConstraintViolation = 0x4000002,
    /** SQLSTATE: `40001` */ TRSerializationFailure = 0x4000001,
    /** SQLSTATE: `40003` */ TRStatementCompletionUnknown = 0x4000003,
    /** SQLSTATE: `40P01` */ TRDeadlockDetected = 0x4020001,

    /* Section: Class 42 - Syntax Error or Access Rule Violation */
    /** SQLSTATE: `42000` */ SyntaxErrorOrAccessRuleViolation = 0x4080000,
    /** SQLSTATE: `42601` */ SyntaxError = 0x4086001,
    /** SQLSTATE: `42501` */ InsufficientPrivilege = 0x4085001,
    /** SQLSTATE: `42846` */ CannotCoerce = 0x4088106,
    /** SQLSTATE: `42803` */ GroupingError = 0x4088003,
    /** SQLSTATE: `42P20` */ WindowingError = 0x40a0080,
    /** SQLSTATE: `42P19` */ InvalidRecursion = 0x40a0049,
    /** SQLSTATE: `42830` */ InvalidForeignKey = 0x40880c0,
    /** SQLSTATE: `42602` */ InvalidName = 0x4086002,
    /** SQLSTATE: `42622` */ NameTooLong = 0x4086082,
    /** SQLSTATE: `42939` */ ReservedName = 0x40890c9,
    /** SQLSTATE: `42804` */ DatatypeMismatch = 0x4088004,
    /** SQLSTATE: `42P18` */ IndeterminateDatatype = 0x40a0048,
    /** SQLSTATE: `42P21` */ CollationMismatch = 0x40a0081,
    /** SQLSTATE: `42P22` */ IndeterminateCollation = 0x40a0082,
    /** SQLSTATE: `42809` */ WrongObjectType = 0x4088009,
    /** SQLSTATE: `428C9` */ GeneratedAlways = 0x40884c9,
    /** SQLSTATE: `42703` */ UndefinedColumn = 0x4087003,
    /** SQLSTATE: `42883` */ UndefinedFunction = 0x4088203,
    /** SQLSTATE: `42P01` */ UndefinedTable = 0x40a0001,
    /** SQLSTATE: `42P02` */ UndefinedParameter = 0x40a0002,
    /** SQLSTATE: `42704` */ UndefinedObject = 0x4087004,
    /** SQLSTATE: `42701` */ DuplicateColumn = 0x4087001,
    /** SQLSTATE: `42P03` */ DuplicateCursor = 0x40a0003,
    /** SQLSTATE: `42P04` */ DuplicateDatabase = 0x40a0004,
    /** SQLSTATE: `42723` */ DuplicateFunction = 0x4087083,
    /** SQLSTATE: `42P05` */ DuplicatePstatement = 0x40a0005,
    /** SQLSTATE: `42P06` */ DuplicateSchema = 0x40a0006,
    /** SQLSTATE: `42P07` */ DuplicateTable = 0x40a0007,
    /** SQLSTATE: `42712` */ DuplicateAlias = 0x4087042,
    /** SQLSTATE: `42710` */ DuplicateObject = 0x4087040,
    /** SQLSTATE: `42702` */ AmbiguousColumn = 0x4087002,
    /** SQLSTATE: `42725` */ AmbiguousFunction = 0x4087085,
    /** SQLSTATE: `42P08` */ AmbiguousParameter = 0x40a0008,
    /** SQLSTATE: `42P09` */ AmbiguousAlias = 0x40a0009,
    /** SQLSTATE: `42P10` */ InvalidColumnReference = 0x40a0040,
    /** SQLSTATE: `42611` */ InvalidColumnDefinition = 0x4086041,
    /** SQLSTATE: `42P11` */ InvalidCursorDefinition = 0x40a0041,
    /** SQLSTATE: `42P12` */ InvalidDatabaseDefinition = 0x40a0042,
    /** SQLSTATE: `42P13` */ InvalidFunctionDefinition = 0x40a0043,
    /** SQLSTATE: `42P14` */ InvalidPstatementDefinition = 0x40a0044,
    /** SQLSTATE: `42P15` */ InvalidSchemaDefinition = 0x40a0045,
    /** SQLSTATE: `42P16` */ InvalidTableDefinition = 0x40a0046,
    /** SQLSTATE: `42P17` */ InvalidObjectDefinition = 0x40a0047,

    /* Section: Class 44 - WITH CHECK OPTION Violation */
    /** SQLSTATE: `44000` */ WithCheckOptionViolation = 0x4100000,

    /* Section: Class 53 - Insufficient Resources */
    /** SQLSTATE: `53000` */ InsufficientResources = 0x50c0000,
    /** SQLSTATE: `53100` */ DiskFull = 0x50c1000,
    /** SQLSTATE: `53200` */ OutOfMemory = 0x50c2000,
    /** SQLSTATE: `53300` */ TooManyConnections = 0x50c3000,
    /** SQLSTATE: `53400` */ ConfigurationLimitExceeded = 0x50c4000,

    /* Section: Class 54 - Program Limit Exceeded */
    /** SQLSTATE: `54000` */ ProgramLimitExceeded = 0x5100000,
    /** SQLSTATE: `54001` */ StatementTooComplex = 0x5100001,
    /** SQLSTATE: `54011` */ TooManyColumns = 0x5100041,
    /** SQLSTATE: `54023` */ TooManyArguments = 0x5100083,

    /* Section: Class 55 - Object Not In Prerequisite State */
    /** SQLSTATE: `55000` */ ObjectNotInPrerequisiteState = 0x5140000,
    /** SQLSTATE: `55006` */ ObjectInUse = 0x5140006,
    /** SQLSTATE: `55P02` */ CantChangeRuntimeParam = 0x5160002,
    /** SQLSTATE: `55P03` */ LockNotAvailable = 0x5160003,
    /** SQLSTATE: `55P04` */ UnsafeNewEnumValueUsage = 0x5160004,

    /* Section: Class 57 - Operator Intervention */
    /** SQLSTATE: `57000` */ OperatorIntervention = 0x51c0000,
    /** SQLSTATE: `57014` */ QueryCanceled = 0x51c0044,
    /** SQLSTATE: `57P01` */ AdminShutdown = 0x51e0001,
    /** SQLSTATE: `57P02` */ CrashShutdown = 0x51e0002,
    /** SQLSTATE: `57P03` */ CannotConnectNow = 0x51e0003,
    /** SQLSTATE: `57P04` */ DatabaseDropped = 0x51e0004,
    /** SQLSTATE: `57P05` */ IdleSessionTimeout = 0x51e0005,

    /* Section: Class 58 - System Error (errors external to PostgreSQL itself) */
    /** SQLSTATE: `58000` */ SystemError = 0x5200000,
    /** SQLSTATE: `58030` */ IoError = 0x52000c0,
    /** SQLSTATE: `58P01` */ UndefinedFile = 0x5220001,
    /** SQLSTATE: `58P02` */ DuplicateFile = 0x5220002,
    /** SQLSTATE: `58P03` */ FileNameTooLong = 0x5220003,

    /* Section: Class F0 - Configuration File Error */
    /** SQLSTATE: `F0000` */ ConfigFileError = 0x16000000,
    /** SQLSTATE: `F0001` */ LockFileExists = 0x16000001,

    /* Section: Class HV - Foreign Data Wrapper Error (SQL/MED) */
    /** SQLSTATE: `HV000` */ FdwError = 0x18980000,
    /** SQLSTATE: `HV005` */ FdwColumnNameNotFound = 0x18980005,
    /** SQLSTATE: `HV002` */ FdwDynamicParameterValueNeeded = 0x18980002,
    /** SQLSTATE: `HV010` */ FdwFunctionSequenceError = 0x18980040,
    /** SQLSTATE: `HV021` */ FdwInconsistentDescriptorInformation = 0x18980081,
    /** SQLSTATE: `HV024` */ FdwInvalidAttributeValue = 0x18980084,
    /** SQLSTATE: `HV007` */ FdwInvalidColumnName = 0x18980007,
    /** SQLSTATE: `HV008` */ FdwInvalidColumnNumber = 0x18980008,
    /** SQLSTATE: `HV004` */ FdwInvalidDataType = 0x18980004,
    /** SQLSTATE: `HV006` */ FdwInvalidDataTypeDescriptors = 0x18980006,
    /** SQLSTATE: `HV091` */ FdwInvalidDescriptorFieldIdentifier = 0x18980241,
    /** SQLSTATE: `HV00B` */ FdwInvalidHandle = 0x18980012,
    /** SQLSTATE: `HV00C` */ FdwInvalidOptionIndex = 0x18980013,
    /** SQLSTATE: `HV00D` */ FdwInvalidOptionName = 0x18980014,
    /** SQLSTATE: `HV090` */ FdwInvalidStringLengthOrBufferLength = 0x18980240,
    /** SQLSTATE: `HV00A` */ FdwInvalidStringFormat = 0x18980011,
    /** SQLSTATE: `HV009` */ FdwInvalidUseOfNullPointer = 0x18980009,
    /** SQLSTATE: `HV014` */ FdwTooManyHandles = 0x18980044,
    /** SQLSTATE: `HV001` */ FdwOutOfMemory = 0x18980001,
    /** SQLSTATE: `HV00P` */ FdwNoSchemas = 0x18980020,
    /** SQLSTATE: `HV00J` */ FdwOptionNameNotFound = 0x1898001a,
    /** SQLSTATE: `HV00K` */ FdwReplyHandle = 0x1898001b,
    /** SQLSTATE: `HV00Q` */ FdwSchemaNotFound = 0x18980021,
    /** SQLSTATE: `HV00R` */ FdwTableNotFound = 0x18980022,
    /** SQLSTATE: `HV00L` */ FdwUnableToCreateExecution = 0x1898001c,
    /** SQLSTATE: `HV00M` */ FdwUnableToCreateReply = 0x1898001d,
    /** SQLSTATE: `HV00N` */ FdwUnableToEstablishConnection = 0x1898001e,

    /* Section: Class P0 - PL/pgSQL Error */
    /** SQLSTATE: `P0000` */ PlpgsqlError = 0x20000000,
    /** SQLSTATE: `P0001` */ RaiseException = 0x20000001,
    /** SQLSTATE: `P0002` */ NoDataFound = 0x20000002,
    /** SQLSTATE: `P0003` */ TooManyRows = 0x20000003,
    /** SQLSTATE: `P0004` */ AssertFailure = 0x20000004,

    /* Section: Class XX - Internal Error */
    /** SQLSTATE: `XX000` */ InternalError = 0x28a00000,
    /** SQLSTATE: `XX001` */ DataCorrupted = 0x28a00001,
    /** SQLSTATE: `XX002` */ IndexCorrupted = 0x28a00002,
}

pub(super) const MAP: mphf::Map<u32, ()> = mphf::Map::new(&SALTS, &ENTRIES);

const ENTRIES: [(u32, ()); 261] = [
    (0x00200006, ()), // 08006 ConnectionFailure
    (0x18980020, ()), // HV00P FdwNoSchemas
    (0x18980084, ()), // HV024 FdwInvalidAttributeValue
    (0x00060001, ()), // 01P01 WarningDeprecatedFeature
    (0x04086041, ()), // 42611 InvalidColumnDefinition
    (0x02080048, ()), // 22018 InvalidCharacterValueForCast
    (0x02080016, ()), // 2200F ZeroLengthCharacterString
    (0x02140007, ()), // 25007 SchemaAndDataStatementMixingNotSupported
    (0x00080001, ()), // 02001 NoAdditionalDynamicResultSetsReturned
    (0x02080087, ()), // 22027 TrimError
    (0x02080012, ()), // 2200B EscapeCharacterConflict
    (0x00200000, ()), // 08000 ConnectionException
    (0x00200001, ()), // 08001 SqlclientUnableToEstablishSqlconnection
    (0x02220001, ()), // 28P01 InvalidPassword
    (0x00200004, ()), // 08004 SqlserverRejectedEstablishmentOfSqlconnection
    (0x02580003, ()), // 2F003 SREProhibitedSqlStatementAttempted
    (0x040a0080, ()), // 42P20 WindowingError
    (0x050c0000, ()), // 53000 InsufficientResources
    (0x040a0001, ()), // 42P01 UndefinedTable
    (0x1898001d, ()), // HV00M FdwUnableToCreateReply
    (0x02180000, ()), // 26000 InvalidSqlStatementName
    (0x00480000, ()), // 0B000 InvalidTransactionInitiation
    (0x00580000, ()), // 0F000 LocatorException
    (0x04087085, ()), // 42725 AmbiguousFunction
    (0x03480000, ()), // 3B000 SavepointException
    (0x00580001, ()), // 0F001 LEInvalidSpecification
    (0x02080052, ()), // 2201B InvalidRegularExpression
    (0x02080068, ()), // 2201X InvalidRowCountInResultOffsetClause
    (0x00a80002, ()), // 0Z002 StackedDiagnosticsAccessedWithoutActiveHandler
    (0x00800000, ()), // 0P000 InvalidRoleSpecification
    (0x02040000, ()), // 21000 CardinalityViolation
    (0x020c0001, ()), // 23001 RestrictViolation
    (0x021c0000, ()), // 27000 TriggeredDataChangeViolation
    (0x02080001, ()), // 22001 StringDataRightTruncation
    (0x20000003, ()), // P0003 TooManyRows
    (0x02080014, ()), // 2200D InvalidEscapeOctet
    (0x02080004, ()), // 22004 NullValueNotAllowed
    (0x040a0045, ()), // 42P15 InvalidSchemaDefinition
    (0x020800c9, ()), // 22039 SqlJsonArrayNotFound
    (0x00440000, ()), // 0A000 FeatureNotSupported
    (0x18980013, ()), // HV00C FdwInvalidOptionIndex
    (0x040884c9, ()), // 428C9 GeneratedAlways
    (0x02080005, ()), // 22005 ErrorInAssignment
    (0x04088009, ()), // 42809 WrongObjectType
    (0x02080009, ()), // 22009 InvalidTimeZoneDisplacementValue
    (0x28a00000, ()), // XX000 InternalError
    (0x0208001d, ()), // 2200M InvalidXmlDocument
    (0x02080024, ()), // 2200T InvalidXmlProcessingInstruction
    (0x00040008, ()), // 01008 WarningImplicitZeroBitPadding
    (0x00220001, ()), // 08P01 ProtocolViolation
    (0x020800c4, ()), // 22034 MoreThanOneSqlJsonItem
    (0x02080040, ()), // 22010 InvalidIndicatorParameterValue
    (0x02160003, ()), // 25P03 IdleInTransactionSessionTimeout
    (0x02080018, ()), // 2200H SequenceGeneratorLimitExceeded
    (0x02080041, ()), // 22011 SubstringError
    (0x04000002, ()), // 40002 TRIntegrityConstraintViolation
    (0x03200004, ()), // 38004 EREReadingSqlDataNotPermitted
    (0x02160002, ()), // 25P02 InFailedSqlTransaction
    (0x18980240, ()), // HV090 FdwInvalidStringLengthOrBufferLength
    (0x051e0003, ()), // 57P03 CannotConnectNow
    (0x03100000, ()), // 34000 InvalidCursorName
    (0x02080084, ()), // 22024 UnterminatedCString
    (0x02080045, ()), // 22015 IntervalFieldOverflow
    (0x02080043, ()), // 22013 InvalidPrecedingOrFollowingSize
    (0x05200000, ()), // 58000 SystemError
    (0x00700000, ()), // 0L000 InvalidGrantor
    (0x02080013, ()), // 2200C InvalidUseOfEscapeCharacter
    (0x02080044, ()), // 22014 InvalidArgumentForNtile
    (0x040a0049, ()), // 42P19 InvalidRecursion
    (0x020800d6, ()), // 2203F SqlJsonScalarRequired
    (0x04087004, ()), // 42704 UndefinedObject
    (0x02080023, ()), // 2200S InvalidXmlComment
    (0x04088004, ()), // 42804 DatatypeMismatch
    (0x020a0001, ()), // 22P01 FloatingPointException
    (0x02080046, ()), // 22016 InvalidArgumentForNthValue
    (0x051e0002, ()), // 57P02 CrashShutdown
    (0x02080067, ()), // 2201W InvalidRowCountInLimitClause
    (0x02000000, ()), // 20000 CaseNotFound
    (0x02080042, ()), // 22012 DivisionByZero
    (0x02080081, ()), // 22021 CharacterNotInRepertoire
    (0x02140004, ()), // 25004 InappropriateIsolationLevelForBranchTransaction
    (0x02140001, ()), // 25001 ActiveSqlTransaction
    (0x02080082, ()), // 22022 IndicatorOverflow
    (0x18980006, ()), // HV006 FdwInvalidDataTypeDescriptors
    (0x02080083, ()), // 22023 InvalidParameterValue
    (0x04087040, ()), // 42710 DuplicateObject
    (0x020800c8, ()), // 22038 SingletonSqlJsonItemRequired
    (0x02080097, ()), // 2202G InvalidTablesampleRepeat
    (0x020800d3, ()), // 2203C SqlJsonObjectNotFound
    (0x02080086, ()), // 22026 StringDataLengthMismatch
    (0x04080000, ()), // 42000 SyntaxErrorOrAccessRuleViolation
    (0x02080098, ()), // 2202H InvalidTablesampleArgument
    (0x04086001, ()), // 42601 SyntaxError
    (0x020800c0, ()), // 22030 DuplicateJsonObjectKeyValue
    (0x020800c1, ()), // 22031 InvalidArgumentForSqlJsonDatetimeFunction
    (0x020800c3, ()), // 22033 InvalidSqlJsonSubscript
    (0x04088106, ()), // 42846 CannotCoerce
    (0x020800d7, ()), // 2203G SqlJsonItemCannotBeCastToTargetType
    (0x18980012, ()), // HV00B FdwInvalidHandle
    (0x020a0002, ()), // 22P02 InvalidTextRepresentation
    (0x020a0006, ()), // 22P06 NonstandardUseOfEscapeCharacter
    (0x20000001, ()), // P0001 RaiseException
    (0x052000c0, ()), // 58030 IoError
    (0x00240000, ()), // 09000 TriggeredActionException
    (0x020c0000, ()), // 23000 IntegrityConstraintViolation
    (0x0208001c, ()), // 2200L NotAnXmlDocument
    (0x020c5003, ()), // 23503 ForeignKeyViolation
    (0x020c5005, ()), // 23505 UniqueViolation
    (0x02080055, ()), // 2201E InvalidArgumentForLog
    (0x02160004, ()), // 25P04 TransactionTimeout
    (0x020c5044, ()), // 23514 CheckViolation
    (0x05100000, ()), // 54000 ProgramLimitExceeded
    (0x05100083, ()), // 54023 TooManyArguments
    (0x00080000, ()), // 02000 NoData
    (0x02140000, ()), // 25000 InvalidTransactionState
    (0x03260003, ()), // 39P03 ERIEEventTriggerProtocolViolated
    (0x02080007, ()), // 22007 InvalidDatetimeFormat
    (0x18980007, ()), // HV007 FdwInvalidColumnName
    (0x02140002, ()), // 25002 BranchTransactionAlreadyActive
    (0x04087042, ()), // 42712 DuplicateAlias
    (0x02140006, ()), // 25006 ReadOnlySqlTransaction
    (0x02140008, ()), // 25008 HeldCursorRequiresSameIsolationLevel
    (0x04088203, ()), // 42883 UndefinedFunction
    (0x024a0001, ()), // 2BP01 DependentObjectsStillExist
    (0x05160004, ()), // 55P04 UnsafeNewEnumValueUsage
    (0x00040006, ()), // 01006 WarningPrivilegeNotRevoked
    (0x02500000, ()), // 2D000 InvalidTransactionTermination
    (0x02580002, ()), // 2F002 SREModifyingSqlDataNotPermitted
    (0x02580004, ()), // 2F004 SREReadingSqlDataNotPermitted
    (0x00720001, ()), // 0LP01 InvalidGrantOperation
    (0x03200002, ()), // 38002 EREModifyingSqlDataNotPermitted
    (0x00200007, ()), // 08007 TransactionResolutionUnknown
    (0x18980022, ()), // HV00R FdwTableNotFound
    (0x02580005, ()), // 2F005 SREFunctionExecutedNoReturnStatement
    (0x05140006, ()), // 55006 ObjectInUse
    (0x02160001, ()), // 25P01 NoActiveSqlTransaction
    (0x040890c9, ()), // 42939 ReservedName
    (0x00a80000, ()), // 0Z000 DiagnosticsException
    (0x03200000, ()), // 38000 ExternalRoutineException
    (0x02200000, ()), // 28000 InvalidAuthorizationSpecification
    (0x02480000, ()), // 2B000 DependentPrivilegeDescriptorsStillExist
    (0x00040004, ()), // 01004 WarningStringDataRightTruncation
    (0x03240001, ()), // 39001 ERIEInvalidSqlstateReturned
    (0x03260001, ()), // 39P01 ERIETriggerProtocolViolated
    (0x020800c6, ()), // 22036 NonNumericSqlJsonItem
    (0x03480001, ()), // 3B001 SEInvalidSpecification
    (0x03580000, ()), // 3F000 InvalidSchemaName
    (0x04000001, ()), // 40001 TRSerializationFailure
    (0x020a0003, ()), // 22P03 InvalidBinaryRepresentation
    (0x04000003, ()), // 40003 TRStatementCompletionUnknown
    (0x050c4000, ()), // 53400 ConfigurationLimitExceeded
    (0x020800c7, ()), // 22037 NonUniqueKeysInAJsonObject
    (0x18980000, ()), // HV000 FdwError
    (0x04020001, ()), // 40P01 TRDeadlockDetected
    (0x02080008, ()), // 22008 DatetimeFieldOverflow
    (0x04085001, ()), // 42501 InsufficientPrivilege
    (0x04086002, ()), // 42602 InvalidName
    (0x05100041, ()), // 54011 TooManyColumns
    (0x18980014, ()), // HV00D FdwInvalidOptionName
    (0x04087002, ()), // 42702 AmbiguousColumn
    (0x04087003, ()), // 42703 UndefinedColumn
    (0x04087083, ()), // 42723 DuplicateFunction
    (0x0208001e, ()), // 2200N InvalidXmlContent
    (0x04088003, ()), // 42803 GroupingError
    (0x18980044, ()), // HV014 FdwTooManyHandles
    (0x03260002, ()), // 39P02 ERIESrfProtocolViolated
    (0x020800c2, ()), // 22032 InvalidJsonText
    (0x040880c0, ()), // 42830 InvalidForeignKey
    (0x05220001, ()), // 58P01 UndefinedFile
    (0x040a0081, ()), // 42P21 CollationMismatch
    (0x00040013, ()), // 0100C WarningDynamicResultSetsReturned
    (0x03200003, ()), // 38003 EREProhibitedSqlStatementAttempted
    (0x02100000, ()), // 24000 InvalidCursorState
    (0x020e0001, ()), // 23P01 ExclusionViolation
    (0x040a0005, ()), // 42P05 DuplicatePstatement
    (0x040a0006, ()), // 42P06 DuplicateSchema
    (0x000c0000, ()), // 03000 SqlStatementNotYetComplete
    (0x020800c5, ()), // 22035 NoSqlJsonItem
    (0x040a0008, ()), // 42P08 AmbiguousParameter
    (0x02080003, ()), // 22003 NumericValueOutOfRange
    (0x040a0009, ()), // 42P09 AmbiguousAlias
    (0x040a0040, ()), // 42P10 InvalidColumnReference
    (0x16000000, ()), // F0000 ConfigFileError
    (0x040a0041, ()), // 42P11 InvalidCursorDefinition
    (0x040a0042, ()), // 42P12 InvalidDatabaseDefinition
    (0x040a0044, ()), // 42P14 InvalidPstatementDefinition
    (0x040a0047, ()), // 42P17 InvalidObjectDefinition
    (0x03240000, ()), // 39000 ExternalRoutineInvocationException
    (0x040a0082, ()), // 42P22 IndeterminateCollation
    (0x040a0004, ()), // 42P04 DuplicateDatabase
    (0x18980021, ()), // HV00Q FdwSchemaNotFound
    (0x02140003, ()), // 25003 InappropriateAccessModeForBranchTransaction
    (0x03240004, ()), // 39004 ERIENullValueNotAllowed
    (0x04100000, ()), // 44000 WithCheckOptionViolation
    (0x050c1000, ()), // 53100 DiskFull
    (0x050c2000, ()), // 53200 OutOfMemory
    (0x040a0046, ()), // 42P16 InvalidTableDefinition
    (0x050c3000, ()), // 53300 TooManyConnections
    (0x05100001, ()), // 54001 StatementTooComplex
    (0x20000002, ()), // P0002 NoDataFound
    (0x020800d2, ()), // 2203B SqlJsonNumberNotFound
    (0x03500000, ()), // 3D000 InvalidCatalogName
    (0x05140000, ()), // 55000 ObjectNotInPrerequisiteState
    (0x00040007, ()), // 01007 WarningPrivilegeNotGranted
    (0x18980005, ()), // HV005 FdwColumnNameNotFound
    (0x00040003, ()), // 01003 WarningNullValueEliminatedInSetFunction
    (0x02080057, ()), // 2201G InvalidArgumentForWidthBucketFunction
    (0x040a0043, ()), // 42P13 InvalidFunctionDefinition
    (0x05160002, ()), // 55P02 CantChangeRuntimeParam
    (0x00040000, ()), // 01000 Warning
    (0x04087001, ()), // 42701 DuplicateColumn
    (0x02080056, ()), // 2201F InvalidArgumentForPowerFunction
    (0x05160003, ()), // 55P03 LockNotAvailable
    (0x040a0048, ()), // 42P18 IndeterminateDatatype
    (0x020a0005, ()), // 22P05 UntranslatableCharacter
    (0x20000000, ()), // P0000 PlpgsqlError
    (0x051c0000, ()), // 57000 OperatorIntervention
    (0x051c0044, ()), // 57014 QueryCanceled
    (0x18980009, ()), // HV009 FdwInvalidUseOfNullPointer
    (0x051e0001, ()), // 57P01 AdminShutdown
    (0x051e0005, ()), // 57P05 IdleSessionTimeout
    (0x040a0002, ()), // 42P02 UndefinedParameter
    (0x020a0004, ()), // 22P04 BadCopyFileFormat
    (0x02080017, ()), // 2200G MostSpecificTypeMismatch
    (0x1898001e, ()), // HV00N FdwUnableToEstablishConnection
    (0x01006008, ()), // 10608 InvalidArgumentForXquery
    (0x05220002, ()), // 58P02 DuplicateFile
    (0x02080085, ()), // 22025 InvalidEscapeSequence
    (0x040a0003, ()), // 42P03 DuplicateCursor
    (0x02140005, ()), // 25005 NoActiveSqlTransactionForBranchTransaction
    (0x05220003, ()), // 58P03 FileNameTooLong
    (0x16000001, ()), // F0001 LockFileExists
    (0x020c5002, ()), // 23502 NotNullViolation
    (0x18980001, ()), // HV001 FdwOutOfMemory
    (0x18980002, ()), // HV002 FdwDynamicParameterValueNeeded
    (0x04000000, ()), // 40000 TransactionRollback
    (0x020800d5, ()), // 2203E TooManyJsonObjectMembers
    (0x051e0004, ()), // 57P04 DatabaseDropped
    (0x00200003, ()), // 08003 ConnectionDoesNotExist
    (0x18980004, ()), // HV004 FdwInvalidDataType
    (0x02080000, ()), // 22000 DataException
    (0x02080002, ()), // 22002 NullValueNoIndicatorParameter
    (0x18980008, ()), // HV008 FdwInvalidColumnNumber
    (0x18980011, ()), // HV00A FdwInvalidStringFormat
    (0x1898001a, ()), // HV00J FdwOptionNameNotFound
    (0x04086082, ()), // 42622 NameTooLong
    (0x1898001b, ()), // HV00K FdwReplyHandle
    (0x040a0007, ()), // 42P07 DuplicateTable
    (0x020800d4, ()), // 2203D TooManyJsonArrayElements
    (0x02080095, ()), // 2202E ArraySubscriptError
    (0x020800d1, ()), // 2203A SqlJsonMemberNotFound
    (0x20000004, ()), // P0004 AssertFailure
    (0x1898001c, ()), // HV00L FdwUnableToCreateExecution
    (0x03200001, ()), // 38001 EREContainingSqlNotPermitted
    (0x18980040, ()), // HV010 FdwFunctionSequenceError
    (0x02080049, ()), // 22019 InvalidEscapeCharacter
    (0x02580000, ()), // 2F000 SqlRoutineException
    (0x18980081, ()), // HV021 FdwInconsistentDescriptorInformation
    (0x18980241, ()), // HV091 FdwInvalidDescriptorFieldIdentifier
    (0x28a00001, ()), // XX001 DataCorrupted
    (0x28a00002, ()), // XX002 IndexCorrupted
];

const SALTS: [i16; 257] = [
     -48,    0, -258,    0,    0, -209, -227, -111,    0,    0,    4, -150,    4, -168,  -31,  -96,
    -261, -101, -164,    2, -187,    2, -175,    0, -253,    4,    0,    2,    0,    0,    3,    9,
       0,    0,    2,    0,    0,    4,   22,  -98,    6,    3,    0,    0,    0,    3, -259,    0,
    -161,    0,    0,   19,    4,    0,    4,    4,    2,  -47, -235, -199,    0,    3,  -92,    0,
       0, -218,  -23,  -30,  -15,    2,    2, -124, -196, -243,    0, -127, -128,  -45,    0,  -68,
    -182,  -22, -245, -154, -234, -247,    0,    0,  -88, -100,    4,    3,    4, -157, -186,    0,
       0,    0,    0,    0, -139,    0,  -43,    2,    2,    0, -203,    2, -198,    0,    2,  -34,
       0,    0,  -83,    0, -107,    2,  -55,    2,    0, -148,    0,    2, -176,    0,    0,    0,
       3,    0, -119,    0,    0,    0,    3,  -12,   10,    0,    4, -213,  -94,    3,    0,    0,
      -9,    2, -179,    0, -181,    0,    0,    3,  -80,    3,    0,    0,    0,    0, -189, -147,
    -156,    8,    4, -232,    2,    0,    0, -244,    2, -184, -115,  -13,    0,    2,    4,    0,
    -195,    2, -194,    0,    2,    2, -231,  -85,    0,  -37, -162,    0,    0,    0, -146, -255,
       0, -221,  -52,    2, -143,    7,    0,    0, -105,  -95,    0, -129,    2,    0,    0, -144,
       6,  -64,    6,    2,  -77, -185,    6,    0,    0,    0,    0, -121, -134,    0,    0,    3,
       0,    2,    0,    2,    0, -260, -240, -220, -217,   -4,    3,    3,    0,    0,    0,    5,
    -160,    0,    6,    0,    0, -108,    0,    0,    5,  -75,    0,    0,    0,  -26, -122,    0,
       2,
];

use crate::mphf;
