pg_basics::reexport! { pub
    add_drop,
    aggregate_with_args,
    alias,
    alter_default_privileges_stmt,
    alter_event_trig_stmt,
    alter_extension_contents_stmt,
    alter_extension_stmt,
    alter_function_stmt,
    alter_object_depends_stmt,
    alter_object_schema_stmt,
    alter_owner_stmt,
    alter_role_option,
    alter_role_set_stmt,
    alter_role_stmt,
    alter_system_stmt,
    alter_user_mapping_stmt,
    binary_expr,
    bool_expr,
    boolean_or_string,
    case_expr,
    column_ref,
    comment_stmt,
    constraints_set_mode,
    constraints_set_stmt,
    create_access_method_stmt,
    create_cast_stmt,
    create_conversion_stmt,
    create_role_option,
    create_role_stmt,
    create_user_mapping_stmt,
    defaultable_value,
    discard_stmt,
    drop_behavior,
    expr_node,
    extract_expr,
    frame_extent,
    func_alias,
    func_args_kind,
    func_call,
    func_call_expr,
    func_expr_windowless,
    function_parameter,
    function_parameter_mode,
    function_table_ref,
    function_with_args,
    generic_option,
    generic_option_kind,
    grant_option,
    grant_stmt,
    graph_table_ref,
    indirection,
    indirection_expr,
    interval_range,
    join_expr,
    join_kind,
    join_qual,
    json,
    json_array_agg,
    json_array_agg_expr,
    json_array_constructor,
    json_array_query_constructor,
    json_behavior,
    json_exists,
    json_format,
    json_key_value,
    json_object,
    json_object_agg,
    json_object_agg_expr,
    json_output,
    json_query,
    json_quotes,
    json_serialize,
    json_table,
    json_table_column_definition,
    json_table_path_spec,
    json_value_expr,
    json_value_func,
    json_wrapper_behavior,
    lock_clause_strength,
    lock_wait_policy,
    locking_clause,
    named_value,
    normalize_func,
    notify_stmt,
    null_treatment,
    numeric_spec,
    one_or_all,
    one_or_both,
    operator,
    operator_with_args,
    over_clause,
    overlay_func,
    paren_table_ref,
    position_func,
    prepare_stmt,
    presence,
    privilege_target,
    qualified_operator,
    range_function,
    range_var,
    raw_stmt,
    reassign_owned_stmt,
    relation_expr,
    relation_name,
    relation_table_ref,
    rename_stmt,
    returning_clause,
    returning_option_kind,
    role_kind,
    role_spec,
    role_stmt,
    rows_table_ref,
    sample_table_ref,
    security_label,
    security_label_stmt,
    select_stmt,
    set_reset_clause,
    set_rest,
    set_rest_more,
    signed_number,
    simple_column_definition,
    sort_by,
    sql_function,
    subselect_table_ref,
    substring_func,
    system_type,
    table_ref,
    transaction_stmt,
    transform,
    trim_func,
    typecast,
    typecast_expr,
    unary_expr,
    unicode_normal_form,
    unique_null_treatment,
    utility_option,
    utility_option_name,
    value_or_default,
    var_value,
    variable_set_stmt,
    variable_target,
    window_definition,
    window_frame,
    xml_element,
    xml_exists,
    xml_node_kind,
    xml_parse,
    xml_processing_instruction,
    xml_root,
    xml_serialize,
    xmltable,
    zone_value,
}

mod database_stmt;
mod graph_pattern;

#[allow(unused_imports)]
pub use {
    database_stmt::alterdb_option::*,
    database_stmt::alterdb_option_kind::*,
    database_stmt::createdb_option::*,
    database_stmt::createdb_option_kind::*,
    database_stmt::createdb_option_value::*,
    database_stmt::database_stmt_option::*,
    database_stmt::*,
    graph_pattern::graph_element_pattern::*,
    graph_pattern::graph_element_pattern_kind::*,
    graph_pattern::*,
};

pub type BinaryOperands = Box<(ExprNode, ExprNode)>;

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum AclOption {
    Schemas(Vec<Str>),
    Roles(Vec<RoleSpec>),
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum SpecificAccessPrivilege {
    AlterSystem,
    Create { columns: Option<Vec<Str>> },
    References { columns: Option<Vec<Str>> },
    Select { columns: Option<Vec<Str>> },
    Named {
        privilege: Str,
        columns: Option<Vec<Str>>
    },
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum AccessPrivilege {
    All { columns: Option<Vec<Str>> },
    Specific(Vec<SpecificAccessPrivilege>),
}

#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum PrivilegeDefaultsTarget {
    Functions,
    LargeObjects,
    Schemas,
    Sequences,
    Tables,
    Types,
}

use pg_basics::Str;
