[package]
name = "postgres-parser-ast"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
elog.workspace = true
postgres-basics.workspace = true
