[package]
name = "pg-ast"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
derive_more = { workspace = true, features = ["from"] }
thiserror.workspace = true
pg-basics.workspace = true
pg-elog.workspace = true
