[workspace]
resolver = "2"

members = [
    "basics",
    "guc",
    "parser",
]

[workspace.package]
edition = "2021"
version = "18.0.0-devel"

[workspace.dependencies]
bitflags = "2"
bitvec = "1"
lazy_static = "1"
phf = { version = "0.11", features = ["macros"] }
thiserror = "1"

postgres-basics = { path = "basics" }
postgres-guc = { path = "guc" }
postgres-parser = { path = "parser" }
