[workspace]
resolver = "3"

members = [
    "basics",
    "guc",
    "parser/ast",
    "parser/error",
    "parser/lexer",
    "parser/parser",
]

[workspace.package]
edition = "2024"
version = "19.0.0-devel"

[workspace.lints.clippy]
useless_conversion = "deny"
items_after_test_module = "allow"

[workspace.lints.rust]
unused_imports = "deny"

[workspace.dependencies]
assert_matches = "1"
bitflags = "2"
bitvec = "1"
lazy_static = "1"
test-case = "3"
thiserror = "2"

postgres-basics = { path = "basics" }
postgres-guc = { path = "guc" }
postgres-parser-ast = { path = "parser/ast" }
postgres-parser-error = { path = "parser/error" }
postgres-parser-lexer = { path = "parser/lexer" }
postgres-parser = { path = "parser/parser" }
