[workspace]
resolver = "2"

members = [
    "basics",
    "guc",
    "parser",
]

[workspace.package]
edition = "2021"
version = "18.0.0-devel"

[workspace.dependencies]
assert_matches = "1"
bitflags = "2"
bitvec = "1"
lazy_static = "1"
test-case = "3"
thiserror = "2"

postgres-basics = { path = "basics" }
postgres-guc = { path = "guc" }
postgres-parser = { path = "parser" }
