[package]
name = "pg-lexer"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
pg-basics.workspace = true
pg-elog.workspace = true

[dev-dependencies]
assert_matches.workspace = true
