[package]
name = "pg-generic-set-ast"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
derive_more = { workspace = true, features = ["from"]}
pg-basics.workspace = true
pg-sink-ast.workspace = true
