use crate::lexer::keyword::Keyword::*;
use bitflags::bitflags;
use phf::phf_map;

#[derive(Debug, Copy, Clone, PartialEq)]
pub struct KeywordDetails {
    pub keyword: Keyword,
    pub text: &'static [u8],
    pub category: KeywordCategory,
    pub bare: bool,
}

impl KeywordDetails {
    pub fn string(&self) -> String {
        unsafe {
            // Simply use `text`, since it's already lowercase
            String::from_utf8_unchecked(self.text.to_vec())
        }
    }
}

const fn keyword(
    keyword: Keyword,
    text: &'static [u8],
    category: KeywordCategory,
    bare: bool,
) -> KeywordDetails {
    KeywordDetails {
        keyword,
        text,
        category,
        bare,
    }
}

bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq)]
    pub struct KeywordCategory: u8 {
        const Unreserved   = 0x01;
        const ColumnName   = 0x02;
        const TypeFuncName = 0x04;
        const Reserved     = 0x08;
    }
}

#[derive(Debug, Copy, Clone, PartialEq)]
pub enum Keyword {
    Abort,
    Absent,
    Absolute,
    Access,
    Action,
    Add,
    Admin,
    After,
    Aggregate,
    All,
    Also,
    Alter,
    Always,
    Analyse,
    Analyze,
    And,
    Any,
    Array,
    As,
    Asc,
    Asensitive,
    Assertion,
    Assignment,
    Asymmetric,
    At,
    Atomic,
    Attach,
    Attribute,
    Authorization,
    Backward,
    Before,
    Begin,
    Between,
    Bigint,
    Binary,
    Bit,
    Boolean,
    Both,
    Breadth,
    By,
    Cache,
    Call,
    Called,
    Cascade,
    Cascaded,
    Case,
    Cast,
    Catalog,
    Chain,
    Char,
    Character,
    Characteristics,
    Check,
    Checkpoint,
    Class,
    Close,
    Cluster,
    Coalesce,
    Collate,
    Collation,
    Column,
    Columns,
    Comment,
    Comments,
    Commit,
    Committed,
    Compression,
    Concurrently,
    Conditional,
    Configuration,
    Conflict,
    Connection,
    Constraint,
    Constraints,
    Content,
    Continue,
    Conversion,
    Copy,
    Cost,
    Create,
    Cross,
    Csv,
    Cube,
    Current,
    CurrentCatalog,
    CurrentDate,
    CurrentRole,
    CurrentSchema,
    CurrentTime,
    CurrentTimestamp,
    CurrentUser,
    Cursor,
    Cycle,
    Data,
    Database,
    Day,
    Deallocate,
    Dec,
    Decimal,
    Declare,
    Default,
    Defaults,
    Deferrable,
    Deferred,
    Definer,
    Delete,
    Delimiter,
    Delimiters,
    Depends,
    Depth,
    Desc,
    Detach,
    Dictionary,
    Disable,
    Discard,
    Distinct,
    Do,
    Document,
    Domain,
    Double,
    Drop,
    Each,
    Else,
    Empty,
    Enable,
    Encoding,
    Encrypted,
    End,
    Enum,
    Error,
    Escape,
    Event,
    Except,
    Exclude,
    Excluding,
    Exclusive,
    Execute,
    Exists,
    Explain,
    Expression,
    Extension,
    External,
    Extract,
    False,
    Family,
    Fetch,
    Filter,
    Finalize,
    First,
    Float,
    Following,
    For,
    Force,
    Foreign,
    Format,
    Forward,
    Freeze,
    From,
    Full,
    Function,
    Functions,
    Generated,
    Global,
    Grant,
    Granted,
    Greatest,
    Group,
    Grouping,
    Groups,
    Handler,
    Having,
    Header,
    Hold,
    Hour,
    Identity,
    If,
    Ilike,
    Immediate,
    Immutable,
    Implicit,
    Import,
    In,
    Include,
    Including,
    Increment,
    Indent,
    Index,
    Indexes,
    Inherit,
    Inherits,
    Initially,
    Inline,
    Inner,
    Inout,
    Input,
    Insensitive,
    Insert,
    Instead,
    Int,
    Integer,
    Intersect,
    Interval,
    Into,
    Invoker,
    Is,
    Isnull,
    Isolation,
    Join,
    Json,
    JsonArray,
    JsonArrayagg,
    JsonExists,
    JsonObject,
    JsonObjectagg,
    JsonQuery,
    JsonScalar,
    JsonSerialize,
    JsonTable,
    JsonValue,
    Keep,
    Key,
    Keys,
    Label,
    Language,
    Large,
    Last,
    Lateral,
    Leading,
    Leakproof,
    Least,
    Left,
    Level,
    Like,
    Limit,
    Listen,
    Load,
    Local,
    Localtime,
    Localtimestamp,
    Location,
    Lock,
    Locked,
    Logged,
    Mapping,
    Match,
    Matched,
    Materialized,
    Maxvalue,
    Merge,
    MergeAction,
    Method,
    Minute,
    Minvalue,
    Mode,
    Month,
    Move,
    Name,
    Names,
    National,
    Natural,
    Nchar,
    Nested,
    New,
    Next,
    Nfc,
    Nfd,
    Nfkc,
    Nfkd,
    No,
    None,
    Normalize,
    Normalized,
    Not,
    Nothing,
    Notify,
    Notnull,
    Nowait,
    Null,
    Nullif,
    Nulls,
    Numeric,
    Object,
    Of,
    Off,
    Offset,
    Oids,
    Old,
    Omit,
    On,
    Only,
    Operator,
    Option,
    Options,
    Or,
    Order,
    Ordinality,
    Others,
    Out,
    Outer,
    Over,
    Overlaps,
    Overlay,
    Overriding,
    Owned,
    Owner,
    Parallel,
    Parameter,
    Parser,
    Partial,
    Partition,
    Passing,
    Password,
    Path,
    Placing,
    Plan,
    Plans,
    Policy,
    Position,
    Preceding,
    Precision,
    Prepare,
    Prepared,
    Preserve,
    Primary,
    Prior,
    Privileges,
    Procedural,
    Procedure,
    Procedures,
    Program,
    Publication,
    Quote,
    Quotes,
    Range,
    Read,
    Real,
    Reassign,
    Recursive,
    Ref,
    References,
    Referencing,
    Refresh,
    Reindex,
    Relative,
    Release,
    Rename,
    Repeatable,
    Replace,
    Replica,
    Reset,
    Restart,
    Restrict,
    Return,
    Returning,
    Returns,
    Revoke,
    Right,
    Role,
    Rollback,
    Rollup,
    Routine,
    Routines,
    Row,
    Rows,
    Rule,
    Savepoint,
    Scalar,
    Schema,
    Schemas,
    Scroll,
    Search,
    Second,
    Security,
    Select,
    Sequence,
    Sequences,
    Serializable,
    Server,
    Session,
    SessionUser,
    Set,
    Setof,
    Sets,
    Share,
    Show,
    Similar,
    Simple,
    Skip,
    Smallint,
    Snapshot,
    Some,
    Source,
    Sql,
    Stable,
    Standalone,
    Start,
    Statement,
    Statistics,
    Stdin,
    Stdout,
    Storage,
    Stored,
    Strict,
    StringKw, // Added Kw suffix so it doesn't clash with std::String
    Strip,
    Subscription,
    Substring,
    Support,
    Symmetric,
    Sysid,
    System,
    SystemUser,
    Table,
    Tables,
    Tablesample,
    Tablespace,
    Target,
    Temp,
    Template,
    Temporary,
    Text,
    Then,
    Ties,
    Time,
    Timestamp,
    To,
    Trailing,
    Transaction,
    Transform,
    Treat,
    Trigger,
    Trim,
    True,
    Truncate,
    Trusted,
    Type,
    Types,
    Uescape,
    Unbounded,
    Uncommitted,
    Unconditional,
    Unencrypted,
    Union,
    Unique,
    Unknown,
    Unlisten,
    Unlogged,
    Until,
    Update,
    User,
    Using,
    Vacuum,
    Valid,
    Validate,
    Validator,
    Value,
    Values,
    Varchar,
    Variadic,
    Varying,
    Verbose,
    Version,
    View,
    Views,
    Volatile,
    When,
    Where,
    Whitespace,
    Window,
    With,
    Within,
    Without,
    Work,
    Wrapper,
    Write,
    Xml,
    Xmlattributes,
    Xmlconcat,
    Xmlelement,
    Xmlexists,
    Xmlforest,
    Xmlnamespaces,
    Xmlparse,
    Xmlpi,
    Xmlroot,
    Xmlserialize,
    Xmltable,
    Year,
    Yes,
    Zone,
}

/// Ensure this map includes all `Keyword`s.
pub(super) static KEYWORDS: phf::Map<&'static [u8], KeywordDetails> = phf_map! {
    b"abort" => keyword(Abort, b"abort", KeywordCategory::Unreserved, true),
    b"absent" => keyword(Absent, b"absent", KeywordCategory::Unreserved, true),
    b"absolute" => keyword(Absolute, b"absolute", KeywordCategory::Unreserved, true),
    b"access" => keyword(Access, b"access", KeywordCategory::Unreserved, true),
    b"action" => keyword(Action, b"action", KeywordCategory::Unreserved, true),
    b"add" => keyword(Add, b"add", KeywordCategory::Unreserved, true),
    b"admin" => keyword(Admin, b"admin", KeywordCategory::Unreserved, true),
    b"after" => keyword(After, b"after", KeywordCategory::Unreserved, true),
    b"aggregate" => keyword(Aggregate, b"aggregate", KeywordCategory::Unreserved, true),
    b"all" => keyword(All, b"all", KeywordCategory::Reserved, true),
    b"also" => keyword(Also, b"also", KeywordCategory::Unreserved, true),
    b"alter" => keyword(Alter, b"alter", KeywordCategory::Unreserved, true),
    b"always" => keyword(Always, b"always", KeywordCategory::Unreserved, true),
    b"analyse" => keyword(Analyse, b"analyse", KeywordCategory::Reserved, true),
    b"analyze" => keyword(Analyze, b"analyze", KeywordCategory::Reserved, true),
    b"and" => keyword(And, b"and", KeywordCategory::Reserved, true),
    b"any" => keyword(Any, b"any", KeywordCategory::Reserved, true),
    b"array" => keyword(Array, b"array", KeywordCategory::Reserved, false),
    b"as" => keyword(As, b"as", KeywordCategory::Reserved, false),
    b"asc" => keyword(Asc, b"asc", KeywordCategory::Reserved, true),
    b"asensitive" => keyword(Asensitive, b"asensitive", KeywordCategory::Unreserved, true),
    b"assertion" => keyword(Assertion, b"assertion", KeywordCategory::Unreserved, true),
    b"assignment" => keyword(Assignment, b"assignment", KeywordCategory::Unreserved, true),
    b"asymmetric" => keyword(Asymmetric, b"asymmetric", KeywordCategory::Reserved, true),
    b"at" => keyword(At, b"at", KeywordCategory::Unreserved, true),
    b"atomic" => keyword(Atomic, b"atomic", KeywordCategory::Unreserved, true),
    b"attach" => keyword(Attach, b"attach", KeywordCategory::Unreserved, true),
    b"attribute" => keyword(Attribute, b"attribute", KeywordCategory::Unreserved, true),
    b"authorization" => keyword(Authorization, b"authorization", KeywordCategory::TypeFuncName, true),
    b"backward" => keyword(Backward, b"backward", KeywordCategory::Unreserved, true),
    b"before" => keyword(Before, b"before", KeywordCategory::Unreserved, true),
    b"begin" => keyword(Begin, b"begin", KeywordCategory::Unreserved, true),
    b"between" => keyword(Between, b"between", KeywordCategory::ColumnName, true),
    b"bigint" => keyword(Bigint, b"bigint", KeywordCategory::ColumnName, true),
    b"binary" => keyword(Binary, b"binary", KeywordCategory::TypeFuncName, true),
    b"bit" => keyword(Bit, b"bit", KeywordCategory::ColumnName, true),
    b"boolean" => keyword(Boolean, b"boolean", KeywordCategory::ColumnName, true),
    b"both" => keyword(Both, b"both", KeywordCategory::Reserved, true),
    b"breadth" => keyword(Breadth, b"breadth", KeywordCategory::Unreserved, true),
    b"by" => keyword(By, b"by", KeywordCategory::Unreserved, true),
    b"cache" => keyword(Cache, b"cache", KeywordCategory::Unreserved, true),
    b"call" => keyword(Call, b"call", KeywordCategory::Unreserved, true),
    b"called" => keyword(Called, b"called", KeywordCategory::Unreserved, true),
    b"cascade" => keyword(Cascade, b"cascade", KeywordCategory::Unreserved, true),
    b"cascaded" => keyword(Cascaded, b"cascaded", KeywordCategory::Unreserved, true),
    b"case" => keyword(Case, b"case", KeywordCategory::Reserved, true),
    b"cast" => keyword(Cast, b"cast", KeywordCategory::Reserved, true),
    b"catalog" => keyword(Catalog, b"catalog", KeywordCategory::Unreserved, true),
    b"chain" => keyword(Chain, b"chain", KeywordCategory::Unreserved, true),
    b"char" => keyword(Char, b"char", KeywordCategory::ColumnName, false),
    b"character" => keyword(Character, b"character", KeywordCategory::ColumnName, false),
    b"characteristics" => keyword(Characteristics, b"characteristics", KeywordCategory::Unreserved, true),
    b"check" => keyword(Check, b"check", KeywordCategory::Reserved, true),
    b"checkpoint" => keyword(Checkpoint, b"checkpoint", KeywordCategory::Unreserved, true),
    b"class" => keyword(Class, b"class", KeywordCategory::Unreserved, true),
    b"close" => keyword(Close, b"close", KeywordCategory::Unreserved, true),
    b"cluster" => keyword(Cluster, b"cluster", KeywordCategory::Unreserved, true),
    b"coalesce" => keyword(Coalesce, b"coalesce", KeywordCategory::ColumnName, true),
    b"collate" => keyword(Collate, b"collate", KeywordCategory::Reserved, true),
    b"collation" => keyword(Collation, b"collation", KeywordCategory::TypeFuncName, true),
    b"column" => keyword(Column, b"column", KeywordCategory::Reserved, true),
    b"columns" => keyword(Columns, b"columns", KeywordCategory::Unreserved, true),
    b"comment" => keyword(Comment, b"comment", KeywordCategory::Unreserved, true),
    b"comments" => keyword(Comments, b"comments", KeywordCategory::Unreserved, true),
    b"commit" => keyword(Commit, b"commit", KeywordCategory::Unreserved, true),
    b"committed" => keyword(Committed, b"committed", KeywordCategory::Unreserved, true),
    b"compression" => keyword(Compression, b"compression", KeywordCategory::Unreserved, true),
    b"concurrently" => keyword(Concurrently, b"concurrently", KeywordCategory::TypeFuncName, true),
    b"conditional" => keyword(Conditional, b"conditional", KeywordCategory::Unreserved, true),
    b"configuration" => keyword(Configuration, b"configuration", KeywordCategory::Unreserved, true),
    b"conflict" => keyword(Conflict, b"conflict", KeywordCategory::Unreserved, true),
    b"connection" => keyword(Connection, b"connection", KeywordCategory::Unreserved, true),
    b"constraint" => keyword(Constraint, b"constraint", KeywordCategory::Reserved, true),
    b"constraints" => keyword(Constraints, b"constraints", KeywordCategory::Unreserved, true),
    b"content" => keyword(Content, b"content", KeywordCategory::Unreserved, true),
    b"continue" => keyword(Continue, b"continue", KeywordCategory::Unreserved, true),
    b"conversion" => keyword(Conversion, b"conversion", KeywordCategory::Unreserved, true),
    b"copy" => keyword(Copy, b"copy", KeywordCategory::Unreserved, true),
    b"cost" => keyword(Cost, b"cost", KeywordCategory::Unreserved, true),
    b"create" => keyword(Create, b"create", KeywordCategory::Reserved, false),
    b"cross" => keyword(Cross, b"cross", KeywordCategory::TypeFuncName, true),
    b"csv" => keyword(Csv, b"csv", KeywordCategory::Unreserved, true),
    b"cube" => keyword(Cube, b"cube", KeywordCategory::Unreserved, true),
    b"current" => keyword(Current, b"current", KeywordCategory::Unreserved, true),
    b"current_catalog" => keyword(CurrentCatalog, b"current_catalog", KeywordCategory::Reserved, true),
    b"current_date" => keyword(CurrentDate, b"current_date", KeywordCategory::Reserved, true),
    b"current_role" => keyword(CurrentRole, b"current_role", KeywordCategory::Reserved, true),
    b"current_schema" => keyword(CurrentSchema, b"current_schema", KeywordCategory::TypeFuncName, true),
    b"current_time" => keyword(CurrentTime, b"current_time", KeywordCategory::Reserved, true),
    b"current_timestamp" => keyword(CurrentTimestamp, b"current_timestamp", KeywordCategory::Reserved, true),
    b"current_user" => keyword(CurrentUser, b"current_user", KeywordCategory::Reserved, true),
    b"cursor" => keyword(Cursor, b"cursor", KeywordCategory::Unreserved, true),
    b"cycle" => keyword(Cycle, b"cycle", KeywordCategory::Unreserved, true),
    b"data" => keyword(Data, b"data", KeywordCategory::Unreserved, true),
    b"database" => keyword(Database, b"database", KeywordCategory::Unreserved, true),
    b"day" => keyword(Day, b"day", KeywordCategory::Unreserved, false),
    b"deallocate" => keyword(Deallocate, b"deallocate", KeywordCategory::Unreserved, true),
    b"dec" => keyword(Dec, b"dec", KeywordCategory::ColumnName, true),
    b"decimal" => keyword(Decimal, b"decimal", KeywordCategory::ColumnName, true),
    b"declare" => keyword(Declare, b"declare", KeywordCategory::Unreserved, true),
    b"default" => keyword(Default, b"default", KeywordCategory::Reserved, true),
    b"defaults" => keyword(Defaults, b"defaults", KeywordCategory::Unreserved, true),
    b"deferrable" => keyword(Deferrable, b"deferrable", KeywordCategory::Reserved, true),
    b"deferred" => keyword(Deferred, b"deferred", KeywordCategory::Unreserved, true),
    b"definer" => keyword(Definer, b"definer", KeywordCategory::Unreserved, true),
    b"delete" => keyword(Delete, b"delete", KeywordCategory::Unreserved, true),
    b"delimiter" => keyword(Delimiter, b"delimiter", KeywordCategory::Unreserved, true),
    b"delimiters" => keyword(Delimiters, b"delimiters", KeywordCategory::Unreserved, true),
    b"depends" => keyword(Depends, b"depends", KeywordCategory::Unreserved, true),
    b"depth" => keyword(Depth, b"depth", KeywordCategory::Unreserved, true),
    b"desc" => keyword(Desc, b"desc", KeywordCategory::Reserved, true),
    b"detach" => keyword(Detach, b"detach", KeywordCategory::Unreserved, true),
    b"dictionary" => keyword(Dictionary, b"dictionary", KeywordCategory::Unreserved, true),
    b"disable" => keyword(Disable, b"disable", KeywordCategory::Unreserved, true),
    b"discard" => keyword(Discard, b"discard", KeywordCategory::Unreserved, true),
    b"distinct" => keyword(Distinct, b"distinct", KeywordCategory::Reserved, true),
    b"do" => keyword(Do, b"do", KeywordCategory::Reserved, true),
    b"document" => keyword(Document, b"document", KeywordCategory::Unreserved, true),
    b"domain" => keyword(Domain, b"domain", KeywordCategory::Unreserved, true),
    b"double" => keyword(Double, b"double", KeywordCategory::Unreserved, true),
    b"drop" => keyword(Drop, b"drop", KeywordCategory::Unreserved, true),
    b"each" => keyword(Each, b"each", KeywordCategory::Unreserved, true),
    b"else" => keyword(Else, b"else", KeywordCategory::Reserved, true),
    b"empty" => keyword(Empty, b"empty", KeywordCategory::Unreserved, true),
    b"enable" => keyword(Enable, b"enable", KeywordCategory::Unreserved, true),
    b"encoding" => keyword(Encoding, b"encoding", KeywordCategory::Unreserved, true),
    b"encrypted" => keyword(Encrypted, b"encrypted", KeywordCategory::Unreserved, true),
    b"end" => keyword(End, b"end", KeywordCategory::Reserved, true),
    b"enum" => keyword(Enum, b"enum", KeywordCategory::Unreserved, true),
    b"error" => keyword(Error, b"error", KeywordCategory::Unreserved, true),
    b"escape" => keyword(Escape, b"escape", KeywordCategory::Unreserved, true),
    b"event" => keyword(Event, b"event", KeywordCategory::Unreserved, true),
    b"except" => keyword(Except, b"except", KeywordCategory::Reserved, false),
    b"exclude" => keyword(Exclude, b"exclude", KeywordCategory::Unreserved, true),
    b"excluding" => keyword(Excluding, b"excluding", KeywordCategory::Unreserved, true),
    b"exclusive" => keyword(Exclusive, b"exclusive", KeywordCategory::Unreserved, true),
    b"execute" => keyword(Execute, b"execute", KeywordCategory::Unreserved, true),
    b"exists" => keyword(Exists, b"exists", KeywordCategory::ColumnName, true),
    b"explain" => keyword(Explain, b"explain", KeywordCategory::Unreserved, true),
    b"expression" => keyword(Expression, b"expression", KeywordCategory::Unreserved, true),
    b"extension" => keyword(Extension, b"extension", KeywordCategory::Unreserved, true),
    b"external" => keyword(External, b"external", KeywordCategory::Unreserved, true),
    b"extract" => keyword(Extract, b"extract", KeywordCategory::ColumnName, true),
    b"false" => keyword(False, b"false", KeywordCategory::Reserved, true),
    b"family" => keyword(Family, b"family", KeywordCategory::Unreserved, true),
    b"fetch" => keyword(Fetch, b"fetch", KeywordCategory::Reserved, false),
    b"filter" => keyword(Filter, b"filter", KeywordCategory::Unreserved, false),
    b"finalize" => keyword(Finalize, b"finalize", KeywordCategory::Unreserved, true),
    b"first" => keyword(First, b"first", KeywordCategory::Unreserved, true),
    b"float" => keyword(Float, b"float", KeywordCategory::ColumnName, true),
    b"following" => keyword(Following, b"following", KeywordCategory::Unreserved, true),
    b"for" => keyword(For, b"for", KeywordCategory::Reserved, false),
    b"force" => keyword(Force, b"force", KeywordCategory::Unreserved, true),
    b"foreign" => keyword(Foreign, b"foreign", KeywordCategory::Reserved, true),
    b"format" => keyword(Format, b"format", KeywordCategory::Unreserved, true),
    b"forward" => keyword(Forward, b"forward", KeywordCategory::Unreserved, true),
    b"freeze" => keyword(Freeze, b"freeze", KeywordCategory::TypeFuncName, true),
    b"from" => keyword(From, b"from", KeywordCategory::Reserved, false),
    b"full" => keyword(Full, b"full", KeywordCategory::TypeFuncName, true),
    b"function" => keyword(Function, b"function", KeywordCategory::Unreserved, true),
    b"functions" => keyword(Functions, b"functions", KeywordCategory::Unreserved, true),
    b"generated" => keyword(Generated, b"generated", KeywordCategory::Unreserved, true),
    b"global" => keyword(Global, b"global", KeywordCategory::Unreserved, true),
    b"grant" => keyword(Grant, b"grant", KeywordCategory::Reserved, false),
    b"granted" => keyword(Granted, b"granted", KeywordCategory::Unreserved, true),
    b"greatest" => keyword(Greatest, b"greatest", KeywordCategory::ColumnName, true),
    b"group" => keyword(Group, b"group", KeywordCategory::Reserved, false),
    b"grouping" => keyword(Grouping, b"grouping", KeywordCategory::ColumnName, true),
    b"groups" => keyword(Groups, b"groups", KeywordCategory::Unreserved, true),
    b"handler" => keyword(Handler, b"handler", KeywordCategory::Unreserved, true),
    b"having" => keyword(Having, b"having", KeywordCategory::Reserved, false),
    b"header" => keyword(Header, b"header", KeywordCategory::Unreserved, true),
    b"hold" => keyword(Hold, b"hold", KeywordCategory::Unreserved, true),
    b"hour" => keyword(Hour, b"hour", KeywordCategory::Unreserved, false),
    b"identity" => keyword(Identity, b"identity", KeywordCategory::Unreserved, true),
    b"if" => keyword(If, b"if", KeywordCategory::Unreserved, true),
    b"ilike" => keyword(Ilike, b"ilike", KeywordCategory::TypeFuncName, true),
    b"immediate" => keyword(Immediate, b"immediate", KeywordCategory::Unreserved, true),
    b"immutable" => keyword(Immutable, b"immutable", KeywordCategory::Unreserved, true),
    b"implicit" => keyword(Implicit, b"implicit", KeywordCategory::Unreserved, true),
    b"import" => keyword(Import, b"import", KeywordCategory::Unreserved, true),
    b"in" => keyword(In, b"in", KeywordCategory::Reserved, true),
    b"include" => keyword(Include, b"include", KeywordCategory::Unreserved, true),
    b"including" => keyword(Including, b"including", KeywordCategory::Unreserved, true),
    b"increment" => keyword(Increment, b"increment", KeywordCategory::Unreserved, true),
    b"indent" => keyword(Indent, b"indent", KeywordCategory::Unreserved, true),
    b"index" => keyword(Index, b"index", KeywordCategory::Unreserved, true),
    b"indexes" => keyword(Indexes, b"indexes", KeywordCategory::Unreserved, true),
    b"inherit" => keyword(Inherit, b"inherit", KeywordCategory::Unreserved, true),
    b"inherits" => keyword(Inherits, b"inherits", KeywordCategory::Unreserved, true),
    b"initially" => keyword(Initially, b"initially", KeywordCategory::Reserved, true),
    b"inline" => keyword(Inline, b"inline", KeywordCategory::Unreserved, true),
    b"inner" => keyword(Inner, b"inner", KeywordCategory::TypeFuncName, true),
    b"inout" => keyword(Inout, b"inout", KeywordCategory::ColumnName, true),
    b"input" => keyword(Input, b"input", KeywordCategory::Unreserved, true),
    b"insensitive" => keyword(Insensitive, b"insensitive", KeywordCategory::Unreserved, true),
    b"insert" => keyword(Insert, b"insert", KeywordCategory::Unreserved, true),
    b"instead" => keyword(Instead, b"instead", KeywordCategory::Unreserved, true),
    b"int" => keyword(Int, b"int", KeywordCategory::ColumnName, true),
    b"integer" => keyword(Integer, b"integer", KeywordCategory::ColumnName, true),
    b"intersect" => keyword(Intersect, b"intersect", KeywordCategory::Reserved, false),
    b"interval" => keyword(Interval, b"interval", KeywordCategory::ColumnName, true),
    b"into" => keyword(Into, b"into", KeywordCategory::Reserved, false),
    b"invoker" => keyword(Invoker, b"invoker", KeywordCategory::Unreserved, true),
    b"is" => keyword(Is, b"is", KeywordCategory::TypeFuncName, true),
    b"isnull" => keyword(Isnull, b"isnull", KeywordCategory::TypeFuncName, false),
    b"isolation" => keyword(Isolation, b"isolation", KeywordCategory::Unreserved, true),
    b"join" => keyword(Join, b"join", KeywordCategory::TypeFuncName, true),
    b"json" => keyword(Json, b"json", KeywordCategory::ColumnName, true),
    b"json_array" => keyword(JsonArray, b"json_array", KeywordCategory::ColumnName, true),
    b"json_arrayagg" => keyword(JsonArrayagg, b"json_arrayagg", KeywordCategory::ColumnName, true),
    b"json_exists" => keyword(JsonExists, b"json_exists", KeywordCategory::ColumnName, true),
    b"json_object" => keyword(JsonObject, b"json_object", KeywordCategory::ColumnName, true),
    b"json_objectagg" => keyword(JsonObjectagg, b"json_objectagg", KeywordCategory::ColumnName, true),
    b"json_query" => keyword(JsonQuery, b"json_query", KeywordCategory::ColumnName, true),
    b"json_scalar" => keyword(JsonScalar, b"json_scalar", KeywordCategory::ColumnName, true),
    b"json_serialize" => keyword(JsonSerialize, b"json_serialize", KeywordCategory::ColumnName, true),
    b"json_table" => keyword(JsonTable, b"json_table", KeywordCategory::ColumnName, true),
    b"json_value" => keyword(JsonValue, b"json_value", KeywordCategory::ColumnName, true),
    b"keep" => keyword(Keep, b"keep", KeywordCategory::Unreserved, true),
    b"key" => keyword(Key, b"key", KeywordCategory::Unreserved, true),
    b"keys" => keyword(Keys, b"keys", KeywordCategory::Unreserved, true),
    b"label" => keyword(Label, b"label", KeywordCategory::Unreserved, true),
    b"language" => keyword(Language, b"language", KeywordCategory::Unreserved, true),
    b"large" => keyword(Large, b"large", KeywordCategory::Unreserved, true),
    b"last" => keyword(Last, b"last", KeywordCategory::Unreserved, true),
    b"lateral" => keyword(Lateral, b"lateral", KeywordCategory::Reserved, true),
    b"leading" => keyword(Leading, b"leading", KeywordCategory::Reserved, true),
    b"leakproof" => keyword(Leakproof, b"leakproof", KeywordCategory::Unreserved, true),
    b"least" => keyword(Least, b"least", KeywordCategory::ColumnName, true),
    b"left" => keyword(Left, b"left", KeywordCategory::TypeFuncName, true),
    b"level" => keyword(Level, b"level", KeywordCategory::Unreserved, true),
    b"like" => keyword(Like, b"like", KeywordCategory::TypeFuncName, true),
    b"limit" => keyword(Limit, b"limit", KeywordCategory::Reserved, false),
    b"listen" => keyword(Listen, b"listen", KeywordCategory::Unreserved, true),
    b"load" => keyword(Load, b"load", KeywordCategory::Unreserved, true),
    b"local" => keyword(Local, b"local", KeywordCategory::Unreserved, true),
    b"localtime" => keyword(Localtime, b"localtime", KeywordCategory::Reserved, true),
    b"localtimestamp" => keyword(Localtimestamp, b"localtimestamp", KeywordCategory::Reserved, true),
    b"location" => keyword(Location, b"location", KeywordCategory::Unreserved, true),
    b"lock" => keyword(Lock, b"lock", KeywordCategory::Unreserved, true),
    b"locked" => keyword(Locked, b"locked", KeywordCategory::Unreserved, true),
    b"logged" => keyword(Logged, b"logged", KeywordCategory::Unreserved, true),
    b"mapping" => keyword(Mapping, b"mapping", KeywordCategory::Unreserved, true),
    b"match" => keyword(Match, b"match", KeywordCategory::Unreserved, true),
    b"matched" => keyword(Matched, b"matched", KeywordCategory::Unreserved, true),
    b"materialized" => keyword(Materialized, b"materialized", KeywordCategory::Unreserved, true),
    b"maxvalue" => keyword(Maxvalue, b"maxvalue", KeywordCategory::Unreserved, true),
    b"merge" => keyword(Merge, b"merge", KeywordCategory::Unreserved, true),
    b"merge_action" => keyword(MergeAction, b"merge_action", KeywordCategory::ColumnName, true),
    b"method" => keyword(Method, b"method", KeywordCategory::Unreserved, true),
    b"minute" => keyword(Minute, b"minute", KeywordCategory::Unreserved, false),
    b"minvalue" => keyword(Minvalue, b"minvalue", KeywordCategory::Unreserved, true),
    b"mode" => keyword(Mode, b"mode", KeywordCategory::Unreserved, true),
    b"month" => keyword(Month, b"month", KeywordCategory::Unreserved, false),
    b"move" => keyword(Move, b"move", KeywordCategory::Unreserved, true),
    b"name" => keyword(Name, b"name", KeywordCategory::Unreserved, true),
    b"names" => keyword(Names, b"names", KeywordCategory::Unreserved, true),
    b"national" => keyword(National, b"national", KeywordCategory::ColumnName, true),
    b"natural" => keyword(Natural, b"natural", KeywordCategory::TypeFuncName, true),
    b"nchar" => keyword(Nchar, b"nchar", KeywordCategory::ColumnName, true),
    b"nested" => keyword(Nested, b"nested", KeywordCategory::Unreserved, true),
    b"new" => keyword(New, b"new", KeywordCategory::Unreserved, true),
    b"next" => keyword(Next, b"next", KeywordCategory::Unreserved, true),
    b"nfc" => keyword(Nfc, b"nfc", KeywordCategory::Unreserved, true),
    b"nfd" => keyword(Nfd, b"nfd", KeywordCategory::Unreserved, true),
    b"nfkc" => keyword(Nfkc, b"nfkc", KeywordCategory::Unreserved, true),
    b"nfkd" => keyword(Nfkd, b"nfkd", KeywordCategory::Unreserved, true),
    b"no" => keyword(No, b"no", KeywordCategory::Unreserved, true),
    b"none" => keyword(None, b"none", KeywordCategory::ColumnName, true),
    b"normalize" => keyword(Normalize, b"normalize", KeywordCategory::ColumnName, true),
    b"normalized" => keyword(Normalized, b"normalized", KeywordCategory::Unreserved, true),
    b"not" => keyword(Not, b"not", KeywordCategory::Reserved, true),
    b"nothing" => keyword(Nothing, b"nothing", KeywordCategory::Unreserved, true),
    b"notify" => keyword(Notify, b"notify", KeywordCategory::Unreserved, true),
    b"notnull" => keyword(Notnull, b"notnull", KeywordCategory::TypeFuncName, false),
    b"nowait" => keyword(Nowait, b"nowait", KeywordCategory::Unreserved, true),
    b"null" => keyword(Null, b"null", KeywordCategory::Reserved, true),
    b"nullif" => keyword(Nullif, b"nullif", KeywordCategory::ColumnName, true),
    b"nulls" => keyword(Nulls, b"nulls", KeywordCategory::Unreserved, true),
    b"numeric" => keyword(Numeric, b"numeric", KeywordCategory::ColumnName, true),
    b"object" => keyword(Object, b"object", KeywordCategory::Unreserved, true),
    b"of" => keyword(Of, b"of", KeywordCategory::Unreserved, true),
    b"off" => keyword(Off, b"off", KeywordCategory::Unreserved, true),
    b"offset" => keyword(Offset, b"offset", KeywordCategory::Reserved, false),
    b"oids" => keyword(Oids, b"oids", KeywordCategory::Unreserved, true),
    b"old" => keyword(Old, b"old", KeywordCategory::Unreserved, true),
    b"omit" => keyword(Omit, b"omit", KeywordCategory::Unreserved, true),
    b"on" => keyword(On, b"on", KeywordCategory::Reserved, false),
    b"only" => keyword(Only, b"only", KeywordCategory::Reserved, true),
    b"operator" => keyword(Operator, b"operator", KeywordCategory::Unreserved, true),
    b"option" => keyword(Option, b"option", KeywordCategory::Unreserved, true),
    b"options" => keyword(Options, b"options", KeywordCategory::Unreserved, true),
    b"or" => keyword(Or, b"or", KeywordCategory::Reserved, true),
    b"order" => keyword(Order, b"order", KeywordCategory::Reserved, false),
    b"ordinality" => keyword(Ordinality, b"ordinality", KeywordCategory::Unreserved, true),
    b"others" => keyword(Others, b"others", KeywordCategory::Unreserved, true),
    b"out" => keyword(Out, b"out", KeywordCategory::ColumnName, true),
    b"outer" => keyword(Outer, b"outer", KeywordCategory::TypeFuncName, true),
    b"over" => keyword(Over, b"over", KeywordCategory::Unreserved, false),
    b"overlaps" => keyword(Overlaps, b"overlaps", KeywordCategory::TypeFuncName, false),
    b"overlay" => keyword(Overlay, b"overlay", KeywordCategory::ColumnName, true),
    b"overriding" => keyword(Overriding, b"overriding", KeywordCategory::Unreserved, true),
    b"owned" => keyword(Owned, b"owned", KeywordCategory::Unreserved, true),
    b"owner" => keyword(Owner, b"owner", KeywordCategory::Unreserved, true),
    b"parallel" => keyword(Parallel, b"parallel", KeywordCategory::Unreserved, true),
    b"parameter" => keyword(Parameter, b"parameter", KeywordCategory::Unreserved, true),
    b"parser" => keyword(Parser, b"parser", KeywordCategory::Unreserved, true),
    b"partial" => keyword(Partial, b"partial", KeywordCategory::Unreserved, true),
    b"partition" => keyword(Partition, b"partition", KeywordCategory::Unreserved, true),
    b"passing" => keyword(Passing, b"passing", KeywordCategory::Unreserved, true),
    b"password" => keyword(Password, b"password", KeywordCategory::Unreserved, true),
    b"path" => keyword(Path, b"path", KeywordCategory::Unreserved, true),
    b"placing" => keyword(Placing, b"placing", KeywordCategory::Reserved, true),
    b"plan" => keyword(Plan, b"plan", KeywordCategory::Unreserved, true),
    b"plans" => keyword(Plans, b"plans", KeywordCategory::Unreserved, true),
    b"policy" => keyword(Policy, b"policy", KeywordCategory::Unreserved, true),
    b"position" => keyword(Position, b"position", KeywordCategory::ColumnName, true),
    b"preceding" => keyword(Preceding, b"preceding", KeywordCategory::Unreserved, true),
    b"precision" => keyword(Precision, b"precision", KeywordCategory::ColumnName, false),
    b"prepare" => keyword(Prepare, b"prepare", KeywordCategory::Unreserved, true),
    b"prepared" => keyword(Prepared, b"prepared", KeywordCategory::Unreserved, true),
    b"preserve" => keyword(Preserve, b"preserve", KeywordCategory::Unreserved, true),
    b"primary" => keyword(Primary, b"primary", KeywordCategory::Reserved, true),
    b"prior" => keyword(Prior, b"prior", KeywordCategory::Unreserved, true),
    b"privileges" => keyword(Privileges, b"privileges", KeywordCategory::Unreserved, true),
    b"procedural" => keyword(Procedural, b"procedural", KeywordCategory::Unreserved, true),
    b"procedure" => keyword(Procedure, b"procedure", KeywordCategory::Unreserved, true),
    b"procedures" => keyword(Procedures, b"procedures", KeywordCategory::Unreserved, true),
    b"program" => keyword(Program, b"program", KeywordCategory::Unreserved, true),
    b"publication" => keyword(Publication, b"publication", KeywordCategory::Unreserved, true),
    b"quote" => keyword(Quote, b"quote", KeywordCategory::Unreserved, true),
    b"quotes" => keyword(Quotes, b"quotes", KeywordCategory::Unreserved, true),
    b"range" => keyword(Range, b"range", KeywordCategory::Unreserved, true),
    b"read" => keyword(Read, b"read", KeywordCategory::Unreserved, true),
    b"real" => keyword(Real, b"real", KeywordCategory::ColumnName, true),
    b"reassign" => keyword(Reassign, b"reassign", KeywordCategory::Unreserved, true),
    b"recursive" => keyword(Recursive, b"recursive", KeywordCategory::Unreserved, true),
    b"ref" => keyword(Ref, b"ref", KeywordCategory::Unreserved, true),
    b"references" => keyword(References, b"references", KeywordCategory::Reserved, true),
    b"referencing" => keyword(Referencing, b"referencing", KeywordCategory::Unreserved, true),
    b"refresh" => keyword(Refresh, b"refresh", KeywordCategory::Unreserved, true),
    b"reindex" => keyword(Reindex, b"reindex", KeywordCategory::Unreserved, true),
    b"relative" => keyword(Relative, b"relative", KeywordCategory::Unreserved, true),
    b"release" => keyword(Release, b"release", KeywordCategory::Unreserved, true),
    b"rename" => keyword(Rename, b"rename", KeywordCategory::Unreserved, true),
    b"repeatable" => keyword(Repeatable, b"repeatable", KeywordCategory::Unreserved, true),
    b"replace" => keyword(Replace, b"replace", KeywordCategory::Unreserved, true),
    b"replica" => keyword(Replica, b"replica", KeywordCategory::Unreserved, true),
    b"reset" => keyword(Reset, b"reset", KeywordCategory::Unreserved, true),
    b"restart" => keyword(Restart, b"restart", KeywordCategory::Unreserved, true),
    b"restrict" => keyword(Restrict, b"restrict", KeywordCategory::Unreserved, true),
    b"return" => keyword(Return, b"return", KeywordCategory::Unreserved, true),
    b"returning" => keyword(Returning, b"returning", KeywordCategory::Reserved, false),
    b"returns" => keyword(Returns, b"returns", KeywordCategory::Unreserved, true),
    b"revoke" => keyword(Revoke, b"revoke", KeywordCategory::Unreserved, true),
    b"right" => keyword(Right, b"right", KeywordCategory::TypeFuncName, true),
    b"role" => keyword(Role, b"role", KeywordCategory::Unreserved, true),
    b"rollback" => keyword(Rollback, b"rollback", KeywordCategory::Unreserved, true),
    b"rollup" => keyword(Rollup, b"rollup", KeywordCategory::Unreserved, true),
    b"routine" => keyword(Routine, b"routine", KeywordCategory::Unreserved, true),
    b"routines" => keyword(Routines, b"routines", KeywordCategory::Unreserved, true),
    b"row" => keyword(Row, b"row", KeywordCategory::ColumnName, true),
    b"rows" => keyword(Rows, b"rows", KeywordCategory::Unreserved, true),
    b"rule" => keyword(Rule, b"rule", KeywordCategory::Unreserved, true),
    b"savepoint" => keyword(Savepoint, b"savepoint", KeywordCategory::Unreserved, true),
    b"scalar" => keyword(Scalar, b"scalar", KeywordCategory::Unreserved, true),
    b"schema" => keyword(Schema, b"schema", KeywordCategory::Unreserved, true),
    b"schemas" => keyword(Schemas, b"schemas", KeywordCategory::Unreserved, true),
    b"scroll" => keyword(Scroll, b"scroll", KeywordCategory::Unreserved, true),
    b"search" => keyword(Search, b"search", KeywordCategory::Unreserved, true),
    b"second" => keyword(Second, b"second", KeywordCategory::Unreserved, false),
    b"security" => keyword(Security, b"security", KeywordCategory::Unreserved, true),
    b"select" => keyword(Select, b"select", KeywordCategory::Reserved, true),
    b"sequence" => keyword(Sequence, b"sequence", KeywordCategory::Unreserved, true),
    b"sequences" => keyword(Sequences, b"sequences", KeywordCategory::Unreserved, true),
    b"serializable" => keyword(Serializable, b"serializable", KeywordCategory::Unreserved, true),
    b"server" => keyword(Server, b"server", KeywordCategory::Unreserved, true),
    b"session" => keyword(Session, b"session", KeywordCategory::Unreserved, true),
    b"session_user" => keyword(SessionUser, b"session_user", KeywordCategory::Reserved, true),
    b"set" => keyword(Set, b"set", KeywordCategory::Unreserved, true),
    b"setof" => keyword(Setof, b"setof", KeywordCategory::ColumnName, true),
    b"sets" => keyword(Sets, b"sets", KeywordCategory::Unreserved, true),
    b"share" => keyword(Share, b"share", KeywordCategory::Unreserved, true),
    b"show" => keyword(Show, b"show", KeywordCategory::Unreserved, true),
    b"similar" => keyword(Similar, b"similar", KeywordCategory::TypeFuncName, true),
    b"simple" => keyword(Simple, b"simple", KeywordCategory::Unreserved, true),
    b"skip" => keyword(Skip, b"skip", KeywordCategory::Unreserved, true),
    b"smallint" => keyword(Smallint, b"smallint", KeywordCategory::ColumnName, true),
    b"snapshot" => keyword(Snapshot, b"snapshot", KeywordCategory::Unreserved, true),
    b"some" => keyword(Some, b"some", KeywordCategory::Reserved, true),
    b"source" => keyword(Source, b"source", KeywordCategory::Unreserved, true),
    b"sql" => keyword(Sql, b"sql", KeywordCategory::Unreserved, true),
    b"stable" => keyword(Stable, b"stable", KeywordCategory::Unreserved, true),
    b"standalone" => keyword(Standalone, b"standalone", KeywordCategory::Unreserved, true),
    b"start" => keyword(Start, b"start", KeywordCategory::Unreserved, true),
    b"statement" => keyword(Statement, b"statement", KeywordCategory::Unreserved, true),
    b"statistics" => keyword(Statistics, b"statistics", KeywordCategory::Unreserved, true),
    b"stdin" => keyword(Stdin, b"stdin", KeywordCategory::Unreserved, true),
    b"stdout" => keyword(Stdout, b"stdout", KeywordCategory::Unreserved, true),
    b"storage" => keyword(Storage, b"storage", KeywordCategory::Unreserved, true),
    b"stored" => keyword(Stored, b"stored", KeywordCategory::Unreserved, true),
    b"strict" => keyword(Strict, b"strict", KeywordCategory::Unreserved, true),
    b"string" => keyword(StringKw, b"string", KeywordCategory::Unreserved, true),
    b"strip" => keyword(Strip, b"strip", KeywordCategory::Unreserved, true),
    b"subscription" => keyword(Subscription, b"subscription", KeywordCategory::Unreserved, true),
    b"substring" => keyword(Substring, b"substring", KeywordCategory::ColumnName, true),
    b"support" => keyword(Support, b"support", KeywordCategory::Unreserved, true),
    b"symmetric" => keyword(Symmetric, b"symmetric", KeywordCategory::Reserved, true),
    b"sysid" => keyword(Sysid, b"sysid", KeywordCategory::Unreserved, true),
    b"system" => keyword(System, b"system", KeywordCategory::Unreserved, true),
    b"system_user" => keyword(SystemUser, b"system_user", KeywordCategory::Reserved, true),
    b"table" => keyword(Table, b"table", KeywordCategory::Reserved, true),
    b"tables" => keyword(Tables, b"tables", KeywordCategory::Unreserved, true),
    b"tablesample" => keyword(Tablesample, b"tablesample", KeywordCategory::TypeFuncName, true),
    b"tablespace" => keyword(Tablespace, b"tablespace", KeywordCategory::Unreserved, true),
    b"target" => keyword(Target, b"target", KeywordCategory::Unreserved, true),
    b"temp" => keyword(Temp, b"temp", KeywordCategory::Unreserved, true),
    b"template" => keyword(Template, b"template", KeywordCategory::Unreserved, true),
    b"temporary" => keyword(Temporary, b"temporary", KeywordCategory::Unreserved, true),
    b"text" => keyword(Text, b"text", KeywordCategory::Unreserved, true),
    b"then" => keyword(Then, b"then", KeywordCategory::Reserved, true),
    b"ties" => keyword(Ties, b"ties", KeywordCategory::Unreserved, true),
    b"time" => keyword(Time, b"time", KeywordCategory::ColumnName, true),
    b"timestamp" => keyword(Timestamp, b"timestamp", KeywordCategory::ColumnName, true),
    b"to" => keyword(To, b"to", KeywordCategory::Reserved, false),
    b"trailing" => keyword(Trailing, b"trailing", KeywordCategory::Reserved, true),
    b"transaction" => keyword(Transaction, b"transaction", KeywordCategory::Unreserved, true),
    b"transform" => keyword(Transform, b"transform", KeywordCategory::Unreserved, true),
    b"treat" => keyword(Treat, b"treat", KeywordCategory::ColumnName, true),
    b"trigger" => keyword(Trigger, b"trigger", KeywordCategory::Unreserved, true),
    b"trim" => keyword(Trim, b"trim", KeywordCategory::ColumnName, true),
    b"true" => keyword(True, b"true", KeywordCategory::Reserved, true),
    b"truncate" => keyword(Truncate, b"truncate", KeywordCategory::Unreserved, true),
    b"trusted" => keyword(Trusted, b"trusted", KeywordCategory::Unreserved, true),
    b"type" => keyword(Type, b"type", KeywordCategory::Unreserved, true),
    b"types" => keyword(Types, b"types", KeywordCategory::Unreserved, true),
    b"uescape" => keyword(Uescape, b"uescape", KeywordCategory::Unreserved, true),
    b"unbounded" => keyword(Unbounded, b"unbounded", KeywordCategory::Unreserved, true),
    b"uncommitted" => keyword(Uncommitted, b"uncommitted", KeywordCategory::Unreserved, true),
    b"unconditional" => keyword(Unconditional, b"unconditional", KeywordCategory::Unreserved, true),
    b"unencrypted" => keyword(Unencrypted, b"unencrypted", KeywordCategory::Unreserved, true),
    b"union" => keyword(Union, b"union", KeywordCategory::Reserved, false),
    b"unique" => keyword(Unique, b"unique", KeywordCategory::Reserved, true),
    b"unknown" => keyword(Unknown, b"unknown", KeywordCategory::Unreserved, true),
    b"unlisten" => keyword(Unlisten, b"unlisten", KeywordCategory::Unreserved, true),
    b"unlogged" => keyword(Unlogged, b"unlogged", KeywordCategory::Unreserved, true),
    b"until" => keyword(Until, b"until", KeywordCategory::Unreserved, true),
    b"update" => keyword(Update, b"update", KeywordCategory::Unreserved, true),
    b"user" => keyword(User, b"user", KeywordCategory::Reserved, true),
    b"using" => keyword(Using, b"using", KeywordCategory::Reserved, true),
    b"vacuum" => keyword(Vacuum, b"vacuum", KeywordCategory::Unreserved, true),
    b"valid" => keyword(Valid, b"valid", KeywordCategory::Unreserved, true),
    b"validate" => keyword(Validate, b"validate", KeywordCategory::Unreserved, true),
    b"validator" => keyword(Validator, b"validator", KeywordCategory::Unreserved, true),
    b"value" => keyword(Value, b"value", KeywordCategory::Unreserved, true),
    b"values" => keyword(Values, b"values", KeywordCategory::ColumnName, true),
    b"varchar" => keyword(Varchar, b"varchar", KeywordCategory::ColumnName, true),
    b"variadic" => keyword(Variadic, b"variadic", KeywordCategory::Reserved, true),
    b"varying" => keyword(Varying, b"varying", KeywordCategory::Unreserved, false),
    b"verbose" => keyword(Verbose, b"verbose", KeywordCategory::TypeFuncName, true),
    b"version" => keyword(Version, b"version", KeywordCategory::Unreserved, true),
    b"view" => keyword(View, b"view", KeywordCategory::Unreserved, true),
    b"views" => keyword(Views, b"views", KeywordCategory::Unreserved, true),
    b"volatile" => keyword(Volatile, b"volatile", KeywordCategory::Unreserved, true),
    b"when" => keyword(When, b"when", KeywordCategory::Reserved, true),
    b"where" => keyword(Where, b"where", KeywordCategory::Reserved, false),
    b"whitespace" => keyword(Whitespace, b"whitespace", KeywordCategory::Unreserved, true),
    b"window" => keyword(Window, b"window", KeywordCategory::Reserved, false),
    b"with" => keyword(With, b"with", KeywordCategory::Reserved, false),
    b"within" => keyword(Within, b"within", KeywordCategory::Unreserved, false),
    b"without" => keyword(Without, b"without", KeywordCategory::Unreserved, false),
    b"work" => keyword(Work, b"work", KeywordCategory::Unreserved, true),
    b"wrapper" => keyword(Wrapper, b"wrapper", KeywordCategory::Unreserved, true),
    b"write" => keyword(Write, b"write", KeywordCategory::Unreserved, true),
    b"xml" => keyword(Xml, b"xml", KeywordCategory::Unreserved, true),
    b"xmlattributes" => keyword(Xmlattributes, b"xmlattributes", KeywordCategory::ColumnName, true),
    b"xmlconcat" => keyword(Xmlconcat, b"xmlconcat", KeywordCategory::ColumnName, true),
    b"xmlelement" => keyword(Xmlelement, b"xmlelement", KeywordCategory::ColumnName, true),
    b"xmlexists" => keyword(Xmlexists, b"xmlexists", KeywordCategory::ColumnName, true),
    b"xmlforest" => keyword(Xmlforest, b"xmlforest", KeywordCategory::ColumnName, true),
    b"xmlnamespaces" => keyword(Xmlnamespaces, b"xmlnamespaces", KeywordCategory::ColumnName, true),
    b"xmlparse" => keyword(Xmlparse, b"xmlparse", KeywordCategory::ColumnName, true),
    b"xmlpi" => keyword(Xmlpi, b"xmlpi", KeywordCategory::ColumnName, true),
    b"xmlroot" => keyword(Xmlroot, b"xmlroot", KeywordCategory::ColumnName, true),
    b"xmlserialize" => keyword(Xmlserialize, b"xmlserialize", KeywordCategory::ColumnName, true),
    b"xmltable" => keyword(Xmltable, b"xmltable", KeywordCategory::ColumnName, true),
    b"year" => keyword(Year, b"year", KeywordCategory::Unreserved, false),
    b"yes" => keyword(Yes, b"yes", KeywordCategory::Unreserved, true),
    b"zone" => keyword(Zone, b"zone", KeywordCategory::Unreserved, true),
};
