[package]
name = "pg-parser"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
derive_more = { workspace = true, features = ["from"] }
pg-ast.workspace = true
pg-basics.workspace = true
pg-combinators.workspace = true
pg-elog.workspace = true
pg-generic-set-combinators.workspace = true
pg-lexer.workspace = true
pg-parser-core.workspace = true
pg-sink-ast.workspace = true
pg-sink-combinators.workspace = true
pg-transaction-mode-ast.workspace = true
pg-transaction-mode-combinators.workspace = true

[dev-dependencies]
assert_matches.workspace = true
test-case.workspace = true
