[package]
name = "pg-parser"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bitvec.workspace = true
derive_more = { workspace = true, features = ["from"] }
pg-ast.workspace = true
pg-basics.workspace = true
pg-elog.workspace = true
pg-lexer.workspace = true

[dev-dependencies]
assert_matches.workspace = true
test-case.workspace = true
