[package]
name = "postgres-parser"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bitflags.workspace = true
bitvec.workspace = true
lazy_static.workspace = true
thiserror.workspace = true
postgres-basics.workspace = true
postgres-parser-error.workspace = true
postgres-parser-lexer.workspace = true

[dev-dependencies]
assert_matches.workspace = true
test-case.workspace = true
