[package]
name = "postgres-parser"
edition.workspace = true
version.workspace = true

[dependencies]
bitflags.workspace = true
bitvec.workspace = true
phf.workspace = true
thiserror.workspace = true
postgres-basics.workspace = true
