
require 'pathname'
require 'rake/clean'

RUST_PROJECT_ROOT = Pathname(__dir__).parent.expand_path
PG_ROOT = RUST_PROJECT_ROOT.parent / 'postgres'

task default: :build

keywords_input = PG_ROOT / 'src/include/parser/kwlist.h'
keywords_output = RUST_PROJECT_ROOT / 'parser/src/lexer/keyword/keywords.rs'
CLEAN << keywords_output
file keywords_output.to_s => keywords_input do | |
  require_relative 'gen-kws.rb'
  KeywordsGenerator.run!(keywords_input, keywords_output)
end

task build: keywords_output
