[package]
name = "pg-elog"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
derive_more = { workspace = true, features = ["display", "error", "from"] }
pg-basics.workspace = true
