/**
 * Groupings to help organize all the run-time options for display.
 * Be sure this agrees with the way the options are categorized in config.sgml!
 */
#[derive(Debug, Default, Clone, Copy, PartialEq)]
pub enum ConfigGroup {
    /// use for options not shown in pg_settings
    #[default]
    Ungrouped,
    FileLocations,
    ConnAuthSettings,
    ConnAuthTcp,
    ConnAuthAuth,
    ConnAuthSsl,
    ResourcesMem,
    ResourcesDisk,
    ResourcesKernel,
    ResourcesVacuumDelay,
    ResourcesBgWriter,
    ResourcesAsynchronous,
    WalSettings,
    WalCheckpoints,
    WalArchiving,
    WalRecovery,
    WalArchiveRecovery,
    WalRecoveryTarget,
    WalSummarization,
    ReplicationSending,
    ReplicationPrimary,
    ReplicationStandby,
    ReplicationSubscribers,
    QueryTuningMethod,
    QueryTuningCost,
    QueryTuningGeqo,
    QueryTuningOther,
    LoggingWhere,
    LoggingWhen,
    LoggingWhat,
    ProcessTitle,
    StatsMonitoring,
    StatsCumulative,
    Autovacuum,
    ClientConnStatement,
    ClientConnLocale,
    ClientConnPreload,
    ClientConnOther,
    LockManagement,
    CompatOptionsPrevious,
    CompatOptionsOther,
    ErrorHandlingOptions,
    PresetOptions,
    CustomOptions,
    DeveloperOptions,
}
